// ══════════════════════════════════════════
// KOERU — HSK2 + HSK3 Vocabulary Data
// Load sau js/pinyin-data.js (HSK1)
// Format giống HSK1_DATA trong pinyin-data.js
// ══════════════════════════════════════════

const HSK2_DATA = [
  // ── Động từ (verbs) ──
  {hanzi:"帮助", pinyin:"bāngzhù",  tone:"1-4", meaning_vi:"giúp đỡ",           hanviet:"bang trợ",    example_zh:"请帮助我。",         example_pinyin:"Qǐng bāngzhù wǒ.",           example_vi:"Xin hãy giúp tôi.", hsk:2},
  {hanzi:"打算", pinyin:"dǎsuàn",   tone:"3-4", meaning_vi:"dự định, có kế hoạch",hanviet:"đả toán",    example_zh:"我打算去北京。",       example_pinyin:"Wǒ dǎsuàn qù Běijīng.",      example_vi:"Tôi dự định đến Bắc Kinh.", hsk:2},
  {hanzi:"担心", pinyin:"dānxīn",   tone:"1-1", meaning_vi:"lo lắng",            hanviet:"đảm tâm",     example_zh:"别担心。",            example_pinyin:"Bié dānxīn.",                example_vi:"Đừng lo lắng.", hsk:2},
  {hanzi:"告诉", pinyin:"gàosu",    tone:"4-0", meaning_vi:"nói cho biết, bảo",  hanviet:"cáo tố",      example_zh:"告诉我你的名字。",     example_pinyin:"Gàosu wǒ nǐ de míngzi.",     example_vi:"Hãy nói tên bạn cho tôi biết.", hsk:2},
  {hanzi:"回答", pinyin:"huídá",    tone:"2-2", meaning_vi:"trả lời",            hanviet:"hồi đáp",     example_zh:"请回答我的问题。",     example_pinyin:"Qǐng huídá wǒ de wèntí.",    example_vi:"Xin hãy trả lời câu hỏi của tôi.", hsk:2},
  {hanzi:"介绍", pinyin:"jièshào",  tone:"4-4", meaning_vi:"giới thiệu",         hanviet:"giới thiệu",  example_zh:"我来介绍一下。",       example_pinyin:"Wǒ lái jièshào yīxià.",      example_vi:"Để tôi giới thiệu một chút.", hsk:2},
  {hanzi:"觉得", pinyin:"juéde",    tone:"2-0", meaning_vi:"cảm thấy, cho rằng", hanviet:"giác đắc",    example_zh:"我觉得很累。",         example_pinyin:"Wǒ juéde hěn lèi.",          example_vi:"Tôi cảm thấy rất mệt.", hsk:2},
  {hanzi:"开始", pinyin:"kāishǐ",   tone:"1-3", meaning_vi:"bắt đầu",            hanviet:"khai thủy",   example_zh:"我们开始上课。",       example_pinyin:"Wǒmen kāishǐ shàngkè.",      example_vi:"Chúng ta bắt đầu học.", hsk:2},
  {hanzi:"练习", pinyin:"liànxí",   tone:"4-2", meaning_vi:"luyện tập",          hanviet:"luyện tập",   example_zh:"每天练习汉语。",       example_pinyin:"Měitiān liànxí Hànyǔ.",      example_vi:"Luyện tập tiếng Trung mỗi ngày.", hsk:2},
  {hanzi:"旅游", pinyin:"lǚyóu",    tone:"3-2", meaning_vi:"du lịch",            hanviet:"lữ du",       example_zh:"我喜欢旅游。",         example_pinyin:"Wǒ xǐhuān lǚyóu.",           example_vi:"Tôi thích du lịch.", hsk:2},
  {hanzi:"明白", pinyin:"míngbai",  tone:"2-0", meaning_vi:"hiểu, rõ ràng",      hanviet:"minh bạch",   example_zh:"你明白了吗？",         example_pinyin:"Nǐ míngbai le ma?",          example_vi:"Bạn hiểu chưa?", hsk:2},
  {hanzi:"认识", pinyin:"rènshi",   tone:"4-0", meaning_vi:"quen biết, nhận ra",  hanviet:"nhận thức",   example_zh:"很高兴认识你。",       example_pinyin:"Hěn gāoxìng rènshi nǐ.",     example_vi:"Rất vui được quen biết bạn.", hsk:2},
  {hanzi:"送",   pinyin:"sòng",     tone:"4",   meaning_vi:"tặng, gửi, tiễn",    hanviet:"tống",        example_zh:"我送你一本书。",       example_pinyin:"Wǒ sòng nǐ yī běn shū.",     example_vi:"Tôi tặng bạn một cuốn sách.", hsk:2},
  {hanzi:"希望", pinyin:"xīwàng",   tone:"1-4", meaning_vi:"hi vọng, mong muốn", hanviet:"hi vọng",     example_zh:"我希望你成功。",       example_pinyin:"Wǒ xīwàng nǐ chénggōng.",   example_vi:"Tôi hi vọng bạn thành công.", hsk:2},
  {hanzi:"游泳", pinyin:"yóuyǒng",  tone:"2-3", meaning_vi:"bơi lội",            hanviet:"du vịnh",     example_zh:"我每天游泳。",         example_pinyin:"Wǒ měitiān yóuyǒng.",        example_vi:"Tôi bơi mỗi ngày.", hsk:2},
  {hanzi:"放",   pinyin:"fàng",     tone:"4",   meaning_vi:"đặt xuống, thả",     hanviet:"phóng",       example_zh:"把书放在桌上。",       example_pinyin:"Bǎ shū fàng zài zhuō shàng.", example_vi:"Đặt sách lên bàn.", hsk:2},
  {hanzi:"借",   pinyin:"jiè",      tone:"4",   meaning_vi:"mượn, cho mượn",     hanviet:"tá",          example_zh:"我可以借你的书吗？",   example_pinyin:"Wǒ kěyǐ jiè nǐ de shū ma?", example_vi:"Tôi có thể mượn sách của bạn không?", hsk:2},
  {hanzi:"复习", pinyin:"fùxí",     tone:"4-2", meaning_vi:"ôn tập",             hanviet:"phục tập",    example_zh:"明天考试，要复习。",   example_pinyin:"Míngtiān kǎoshì, yào fùxí.", example_vi:"Ngày mai thi, cần ôn bài.", hsk:2},
  {hanzi:"比较", pinyin:"bǐjiào",   tone:"3-4", meaning_vi:"so sánh, khá là",    hanviet:"tỉ giảo",     example_zh:"这个比较便宜。",       example_pinyin:"Zhège bǐjiào piányí.",        example_vi:"Cái này khá rẻ.", hsk:2},
  {hanzi:"出发", pinyin:"chūfā",    tone:"1-1", meaning_vi:"xuất phát, khởi hành",hanviet:"xuất phát",  example_zh:"我们明天出发。",       example_pinyin:"Wǒmen míngtiān chūfā.",      example_vi:"Chúng tôi khởi hành ngày mai.", hsk:2},
  // ── Tính từ (adjectives) ──
  {hanzi:"方便", pinyin:"fāngbiàn", tone:"1-4", meaning_vi:"tiện lợi",           hanviet:"phương tiện", example_zh:"这里交通很方便。",     example_pinyin:"Zhèlǐ jiāotōng hěn fāngbiàn.", example_vi:"Giao thông ở đây rất tiện lợi.", hsk:2},
  {hanzi:"容易", pinyin:"róngyì",   tone:"2-4", meaning_vi:"dễ dàng",            hanviet:"dung dị",     example_zh:"汉语不容易。",         example_pinyin:"Hànyǔ bù róngyì.",           example_vi:"Tiếng Trung không dễ.", hsk:2},
  {hanzi:"清楚", pinyin:"qīngchǔ",  tone:"1-3", meaning_vi:"rõ ràng",            hanviet:"thanh sở",    example_zh:"请说清楚一点。",       example_pinyin:"Qǐng shuō qīngchǔ yīdiǎn.",  example_vi:"Xin nói rõ ràng hơn.", hsk:2},
  {hanzi:"漂亮", pinyin:"piàoliang",tone:"4-0", meaning_vi:"đẹp",                hanviet:"phiêu lượng", example_zh:"她很漂亮。",           example_pinyin:"Tā hěn piàoliang.",          example_vi:"Cô ấy rất đẹp.", hsk:2},
  {hanzi:"便宜", pinyin:"piányí",   tone:"2-2", meaning_vi:"rẻ (giá cả)",        hanviet:"tiện nghi",   example_zh:"这件衣服很便宜。",     example_pinyin:"Zhè jiàn yīfu hěn piányí.",  example_vi:"Cái áo này rất rẻ.", hsk:2},
  {hanzi:"贵",   pinyin:"guì",      tone:"4",   meaning_vi:"đắt (giá cả)",       hanviet:"quý",         example_zh:"这太贵了。",           example_pinyin:"Zhè tài guì le.",             example_vi:"Cái này quá đắt.", hsk:2},
  {hanzi:"安静", pinyin:"ānjìng",   tone:"1-4", meaning_vi:"yên tĩnh",           hanviet:"an tĩnh",     example_zh:"图书馆很安静。",       example_pinyin:"Túshūguǎn hěn ānjìng.",      example_vi:"Thư viện rất yên tĩnh.", hsk:2},
  {hanzi:"健康", pinyin:"jiànkāng", tone:"4-1", meaning_vi:"khỏe mạnh",          hanviet:"kiện khang",  example_zh:"身体健康最重要。",     example_pinyin:"Shēntǐ jiànkāng zuì zhòngyào.", example_vi:"Cơ thể khỏe mạnh là quan trọng nhất.", hsk:2},
  // ── Danh từ (nouns) ──
  {hanzi:"超市", pinyin:"chāoshì",  tone:"1-4", meaning_vi:"siêu thị",           hanviet:"siêu thị",    example_zh:"我去超市买东西。",     example_pinyin:"Wǒ qù chāoshì mǎi dōngxi.",  example_vi:"Tôi đi siêu thị mua đồ.", hsk:2},
  {hanzi:"地铁", pinyin:"dìtiě",    tone:"4-3", meaning_vi:"tàu điện ngầm",      hanviet:"địa thiết",   example_zh:"坐地铁去吧。",         example_pinyin:"Zuò dìtiě qù ba.",            example_vi:"Đi tàu điện ngầm đi.", hsk:2},
  {hanzi:"东西", pinyin:"dōngxi",   tone:"1-0", meaning_vi:"đồ vật, thứ gì đó",  hanviet:"đông tây",    example_zh:"你买什么东西？",       example_pinyin:"Nǐ mǎi shénme dōngxi?",      example_vi:"Bạn mua thứ gì vậy?", hsk:2},
  {hanzi:"公司", pinyin:"gōngsī",   tone:"1-1", meaning_vi:"công ty",            hanviet:"công ty",     example_zh:"我在一家公司工作。",   example_pinyin:"Wǒ zài yī jiā gōngsī gōngzuò.", example_vi:"Tôi làm việc ở một công ty.", hsk:2},
  {hanzi:"护照", pinyin:"hùzhào",   tone:"4-4", meaning_vi:"hộ chiếu",           hanviet:"hộ chiếu",    example_zh:"请出示护照。",         example_pinyin:"Qǐng chūshì hùzhào.",        example_vi:"Xin trình hộ chiếu.", hsk:2},
  {hanzi:"机场", pinyin:"jīchǎng",  tone:"1-3", meaning_vi:"sân bay",            hanviet:"cơ trường",   example_zh:"我去机场接朋友。",     example_pinyin:"Wǒ qù jīchǎng jiē péngyǒu.", example_vi:"Tôi đi sân bay đón bạn.", hsk:2},
  {hanzi:"鸡蛋", pinyin:"jīdàn",    tone:"1-4", meaning_vi:"trứng gà",           hanviet:"kê đản",      example_zh:"我每天吃一个鸡蛋。",   example_pinyin:"Wǒ měitiān chī yī gè jīdàn.", example_vi:"Tôi ăn một quả trứng mỗi ngày.", hsk:2},
  {hanzi:"问题", pinyin:"wèntí",    tone:"4-2", meaning_vi:"câu hỏi, vấn đề",    hanviet:"vấn đề",      example_zh:"你有什么问题？",       example_pinyin:"Nǐ yǒu shénme wèntí?",       example_vi:"Bạn có câu hỏi gì không?", hsk:2},
  {hanzi:"身体", pinyin:"shēntǐ",   tone:"1-3", meaning_vi:"cơ thể, sức khỏe",  hanviet:"thân thể",    example_zh:"注意身体。",           example_pinyin:"Zhùyì shēntǐ.",              example_vi:"Chú ý giữ gìn sức khỏe.", hsk:2},
  {hanzi:"生日", pinyin:"shēngrì",  tone:"1-4", meaning_vi:"sinh nhật",          hanviet:"sinh nhật",   example_zh:"今天是我的生日。",     example_pinyin:"Jīntiān shì wǒ de shēngrì.",  example_vi:"Hôm nay là sinh nhật của tôi.", hsk:2},
  {hanzi:"时候", pinyin:"shíhou",   tone:"2-0", meaning_vi:"lúc, khi, thời điểm",hanviet:"thời hậu",   example_zh:"你什么时候来？",       example_pinyin:"Nǐ shénme shíhou lái?",       example_vi:"Khi nào bạn đến?", hsk:2},
  {hanzi:"世界", pinyin:"shìjiè",   tone:"4-4", meaning_vi:"thế giới",           hanviet:"thế giới",    example_zh:"世界很大。",           example_pinyin:"Shìjiè hěn dà.",              example_vi:"Thế giới rất rộng lớn.", hsk:2},
  {hanzi:"手表", pinyin:"shǒubiǎo", tone:"3-3", meaning_vi:"đồng hồ đeo tay",   hanviet:"thủ biểu",    example_zh:"这块手表很贵。",       example_pinyin:"Zhè kuài shǒubiǎo hěn guì.",  example_vi:"Chiếc đồng hồ này rất đắt.", hsk:2},
  {hanzi:"城市", pinyin:"chéngshì", tone:"2-4", meaning_vi:"thành phố",          hanviet:"thành thị",   example_zh:"北京是大城市。",       example_pinyin:"Běijīng shì dà chéngshì.",    example_vi:"Bắc Kinh là thành phố lớn.", hsk:2},
  {hanzi:"地图", pinyin:"dìtú",     tone:"4-2", meaning_vi:"bản đồ",             hanviet:"địa đồ",      example_zh:"请给我一张地图。",     example_pinyin:"Qǐng gěi wǒ yī zhāng dìtú.",  example_vi:"Vui lòng cho tôi một tờ bản đồ.", hsk:2},
  {hanzi:"冰箱", pinyin:"bīngxiāng",tone:"1-1", meaning_vi:"tủ lạnh",           hanviet:"băng tương",  example_zh:"冰箱里有牛奶。",       example_pinyin:"Bīngxiāng lǐ yǒu niúnǎi.",   example_vi:"Trong tủ lạnh có sữa.", hsk:2},
  {hanzi:"报纸", pinyin:"bàozhǐ",   tone:"4-3", meaning_vi:"báo giấy",           hanviet:"báo chỉ",     example_zh:"爸爸在看报纸。",       example_pinyin:"Bàba zài kàn bàozhǐ.",        example_vi:"Bố đang đọc báo.", hsk:2},
  // ── Phó từ / Liên từ (adverbs / conjunctions) ──
  {hanzi:"才",   pinyin:"cái",      tone:"2",   meaning_vi:"mới, vừa mới",       hanviet:"tài",         example_zh:"我才到家。",           example_pinyin:"Wǒ cái dào jiā.",             example_vi:"Tôi vừa mới về nhà.", hsk:2},
  {hanzi:"当然", pinyin:"dāngrán",  tone:"1-2", meaning_vi:"tất nhiên, dĩ nhiên",hanviet:"đương nhiên", example_zh:"当然可以。",           example_pinyin:"Dāngrán kěyǐ.",               example_vi:"Tất nhiên được.", hsk:2},
  {hanzi:"刚才", pinyin:"gāngcái",  tone:"1-2", meaning_vi:"vừa mới (xong)",     hanviet:"cương tài",   example_zh:"刚才谁来了？",         example_pinyin:"Gāngcái shéi lái le?",        example_vi:"Vừa rồi ai đến vậy?", hsk:2},
  {hanzi:"马上", pinyin:"mǎshàng",  tone:"3-4", meaning_vi:"ngay lập tức",       hanviet:"mã thượng",   example_zh:"我马上来。",           example_pinyin:"Wǒ mǎshàng lái.",             example_vi:"Tôi đến ngay.", hsk:2},
  {hanzi:"已经", pinyin:"yǐjīng",   tone:"3-1", meaning_vi:"đã (rồi)",           hanviet:"dĩ kinh",     example_zh:"他已经走了。",         example_pinyin:"Tā yǐjīng zǒu le.",           example_vi:"Anh ấy đã đi rồi.", hsk:2},
  {hanzi:"因为", pinyin:"yīnwèi",   tone:"1-4", meaning_vi:"vì, bởi vì",         hanviet:"nhân vi",     example_zh:"因为下雨，所以没去。", example_pinyin:"Yīnwèi xià yǔ, suǒyǐ méi qù.", example_vi:"Vì trời mưa nên không đi.", hsk:2},
  {hanzi:"如果", pinyin:"rúguǒ",    tone:"2-3", meaning_vi:"nếu như",            hanviet:"như quả",     example_zh:"如果你来，我很高兴。", example_pinyin:"Rúguǒ nǐ lái, wǒ hěn gāoxìng.", example_vi:"Nếu bạn đến, tôi rất vui.", hsk:2},
  {hanzi:"其实", pinyin:"qíshí",    tone:"2-2", meaning_vi:"thực ra, thực tế",   hanviet:"kỳ thực",     example_zh:"其实我不喜欢。",       example_pinyin:"Qíshí wǒ bù xǐhuān.",        example_vi:"Thực ra tôi không thích.", hsk:2},
  {hanzi:"一起", pinyin:"yīqǐ",     tone:"1-3", meaning_vi:"cùng nhau",          hanviet:"nhất khởi",   example_zh:"我们一起去吧。",       example_pinyin:"Wǒmen yīqǐ qù ba.",           example_vi:"Chúng mình cùng nhau đi nhé.", hsk:2},
  {hanzi:"别",   pinyin:"bié",      tone:"2",   meaning_vi:"đừng, chớ",          hanviet:"biệt",        example_zh:"别说话！",             example_pinyin:"Bié shuōhuà!",                example_vi:"Đừng nói chuyện!", hsk:2},
  {hanzi:"更",   pinyin:"gèng",     tone:"4",   meaning_vi:"càng, hơn",          hanviet:"cánh",        example_zh:"今天更冷。",           example_pinyin:"Jīntiān gèng lěng.",          example_vi:"Hôm nay càng lạnh hơn.", hsk:2},
  {hanzi:"或者", pinyin:"huòzhě",   tone:"4-3", meaning_vi:"hoặc là (lựa chọn)", hanviet:"hoặc giả",    example_zh:"喝茶或者喝咖啡？",     example_pinyin:"Hē chá huòzhě hē kāfēi?",    example_vi:"Uống trà hay cà phê?", hsk:2},
  {hanzi:"从",   pinyin:"cóng",     tone:"2",   meaning_vi:"từ (xuất phát điểm)",hanviet:"tùng",        example_zh:"从北京到上海。",       example_pinyin:"Cóng Běijīng dào Shànghǎi.",  example_vi:"Từ Bắc Kinh đến Thượng Hải.", hsk:2},
];

const HSK3_DATA = [
  // ── Động từ (verbs) ──
  {hanzi:"参加", pinyin:"cānjiā",   tone:"1-1", meaning_vi:"tham gia",           hanviet:"tham gia",    example_zh:"我参加了比赛。",       example_pinyin:"Wǒ cānjiā le bǐsài.",        example_vi:"Tôi đã tham gia cuộc thi.", hsk:3},
  {hanzi:"保护", pinyin:"bǎohù",    tone:"3-4", meaning_vi:"bảo vệ",             hanviet:"bảo hộ",      example_zh:"保护环境很重要。",     example_pinyin:"Bǎohù huánjìng hěn zhòngyào.", example_vi:"Bảo vệ môi trường rất quan trọng.", hsk:3},
  {hanzi:"决定", pinyin:"juédìng",  tone:"2-4", meaning_vi:"quyết định",         hanviet:"quyết định",  example_zh:"我决定去留学。",       example_pinyin:"Wǒ juédìng qù liúxué.",       example_vi:"Tôi quyết định đi du học.", hsk:3},
  {hanzi:"坚持", pinyin:"jiānchí",  tone:"1-2", meaning_vi:"kiên trì, tiếp tục", hanviet:"kiên trì",    example_zh:"坚持每天学习。",       example_pinyin:"Jiānchí měitiān xuéxí.",      example_vi:"Kiên trì học tập mỗi ngày.", hsk:3},
  {hanzi:"发展", pinyin:"fāzhǎn",   tone:"1-3", meaning_vi:"phát triển",         hanviet:"phát triển",  example_zh:"经济快速发展。",       example_pinyin:"Jīngjì kuàisù fāzhǎn.",       example_vi:"Kinh tế phát triển nhanh chóng.", hsk:3},
  {hanzi:"管理", pinyin:"guǎnlǐ",   tone:"3-3", meaning_vi:"quản lý",            hanviet:"quản lý",     example_zh:"他管理这家公司。",     example_pinyin:"Tā guǎnlǐ zhè jiā gōngsī.",  example_vi:"Anh ấy quản lý công ty này.", hsk:3},
  {hanzi:"建议", pinyin:"jiànyì",   tone:"4-4", meaning_vi:"đề xuất, gợi ý",     hanviet:"kiến nghị",   example_zh:"我建议你休息一下。",   example_pinyin:"Wǒ jiànyì nǐ xiūxi yīxià.",  example_vi:"Tôi gợi ý bạn nghỉ ngơi một chút.", hsk:3},
  {hanzi:"减少", pinyin:"jiǎnshǎo", tone:"3-3", meaning_vi:"giảm bớt, giảm thiểu",hanviet:"giảm thiểu", example_zh:"减少浪费。",          example_pinyin:"Jiǎnshǎo làngfèi.",           example_vi:"Giảm thiểu lãng phí.", hsk:3},
  {hanzi:"检查", pinyin:"jiǎnchá",  tone:"3-2", meaning_vi:"kiểm tra",           hanviet:"kiểm tra",    example_zh:"医生检查了我的身体。", example_pinyin:"Yīshēng jiǎnchá le wǒ de shēntǐ.", example_vi:"Bác sĩ đã kiểm tra sức khỏe của tôi.", hsk:3},
  {hanzi:"联系", pinyin:"liánxi",   tone:"2-4", meaning_vi:"liên hệ, liên lạc",  hanviet:"liên hệ",     example_zh:"请联系我。",           example_pinyin:"Qǐng liánxi wǒ.",             example_vi:"Vui lòng liên hệ với tôi.", hsk:3},
  {hanzi:"培养", pinyin:"péiyǎng",  tone:"2-3", meaning_vi:"bồi dưỡng, nuôi dưỡng",hanviet:"bồi dưỡng", example_zh:"培养好习惯。",        example_pinyin:"Péiyǎng hǎo xíguàn.",         example_vi:"Bồi dưỡng thói quen tốt.", hsk:3},
  {hanzi:"提高", pinyin:"tígāo",    tone:"2-1", meaning_vi:"nâng cao, cải thiện", hanviet:"đề cao",      example_zh:"提高汉语水平。",       example_pinyin:"Tígāo Hànyǔ shuǐpíng.",       example_vi:"Nâng cao trình độ tiếng Trung.", hsk:3},
  {hanzi:"认为", pinyin:"rènwéi",   tone:"4-2", meaning_vi:"cho rằng, nghĩ rằng",hanviet:"nhận vi",     example_zh:"我认为这是对的。",     example_pinyin:"Wǒ rènwéi zhè shì duì de.",  example_vi:"Tôi cho rằng điều này là đúng.", hsk:3},
  {hanzi:"完成", pinyin:"wánchéng", tone:"2-2", meaning_vi:"hoàn thành",         hanviet:"hoàn thành",  example_zh:"任务完成了。",         example_pinyin:"Rènwù wánchéng le.",          example_vi:"Nhiệm vụ đã hoàn thành.", hsk:3},
  {hanzi:"影响", pinyin:"yǐngxiǎng",tone:"3-3", meaning_vi:"ảnh hưởng",         hanviet:"ảnh hưởng",   example_zh:"天气影响心情。",       example_pinyin:"Tiānqì yǐngxiǎng xīnqíng.",  example_vi:"Thời tiết ảnh hưởng đến tâm trạng.", hsk:3},
  {hanzi:"选择", pinyin:"xuǎnzé",   tone:"3-2", meaning_vi:"lựa chọn",           hanviet:"tuyển trạch", example_zh:"你有很多选择。",       example_pinyin:"Nǐ yǒu hěnduō xuǎnzé.",      example_vi:"Bạn có rất nhiều lựa chọn.", hsk:3},
  {hanzi:"解决", pinyin:"jiějué",   tone:"3-2", meaning_vi:"giải quyết",         hanviet:"giải quyết",  example_zh:"一起来解决问题。",     example_pinyin:"Yīqǐ lái jiějué wèntí.",      example_vi:"Cùng nhau giải quyết vấn đề.", hsk:3},
  {hanzi:"包括", pinyin:"bāokuò",   tone:"1-4", meaning_vi:"bao gồm",            hanviet:"bao quát",    example_zh:"包括所有人。",         example_pinyin:"Bāokuò suǒyǒu rén.",          example_vi:"Bao gồm tất cả mọi người.", hsk:3},
  {hanzi:"继续", pinyin:"jìxù",     tone:"4-4", meaning_vi:"tiếp tục",           hanviet:"kế tục",      example_zh:"请继续说。",           example_pinyin:"Qǐng jìxù shuō.",             example_vi:"Xin tiếp tục nói.", hsk:3},
  {hanzi:"回忆", pinyin:"huíyì",    tone:"2-4", meaning_vi:"hồi tưởng, kỷ niệm", hanviet:"hồi ức",     example_zh:"我喜欢回忆童年。",     example_pinyin:"Wǒ xǐhuān huíyì tóngnián.",  example_vi:"Tôi thích hồi tưởng tuổi thơ.", hsk:3},
  // ── Tính từ (adjectives) ──
  {hanzi:"复杂", pinyin:"fùzá",     tone:"4-2", meaning_vi:"phức tạp",           hanviet:"phức tạp",    example_zh:"这个问题很复杂。",     example_pinyin:"Zhège wèntí hěn fùzá.",       example_vi:"Vấn đề này rất phức tạp.", hsk:3},
  {hanzi:"满意", pinyin:"mǎnyì",    tone:"3-4", meaning_vi:"hài lòng, thỏa mãn", hanviet:"mãn ý",       example_zh:"我对结果很满意。",     example_pinyin:"Wǒ duì jiéguǒ hěn mǎnyì.",   example_vi:"Tôi rất hài lòng với kết quả.", hsk:3},
  {hanzi:"普通", pinyin:"pǔtōng",   tone:"3-1", meaning_vi:"bình thường, phổ thông",hanviet:"phổ thông", example_zh:"这是普通话。",        example_pinyin:"Zhè shì pǔtōnghuà.",          example_vi:"Đây là tiếng phổ thông.", hsk:3},
  {hanzi:"认真", pinyin:"rènzhēn",  tone:"4-1", meaning_vi:"nghiêm túc, cẩn thận",hanviet:"nhận chân",  example_zh:"他工作很认真。",       example_pinyin:"Tā gōngzuò hěn rènzhēn.",     example_vi:"Anh ấy làm việc rất nghiêm túc.", hsk:3},
  {hanzi:"开心", pinyin:"kāixīn",   tone:"1-1", meaning_vi:"vui vẻ, vui mừng",   hanviet:"khai tâm",    example_zh:"今天很开心。",         example_pinyin:"Jīntiān hěn kāixīn.",         example_vi:"Hôm nay rất vui.", hsk:3},
  {hanzi:"安全", pinyin:"ānquán",   tone:"1-2", meaning_vi:"an toàn",            hanviet:"an toàn",     example_zh:"注意交通安全。",       example_pinyin:"Zhùyì jiāotōng ānquán.",      example_vi:"Chú ý an toàn giao thông.", hsk:3},
  {hanzi:"成功", pinyin:"chénggōng",tone:"2-1", meaning_vi:"thành công",         hanviet:"thành công",  example_zh:"祝你成功！",           example_pinyin:"Zhù nǐ chénggōng!",           example_vi:"Chúc bạn thành công!", hsk:3},
  {hanzi:"重要", pinyin:"zhòngyào", tone:"4-4", meaning_vi:"quan trọng",         hanviet:"trọng yếu",   example_zh:"健康最重要。",         example_pinyin:"Jiànkāng zuì zhòngyào.",      example_vi:"Sức khỏe là quan trọng nhất.", hsk:3},
  {hanzi:"负责", pinyin:"fùzé",     tone:"4-2", meaning_vi:"có trách nhiệm",     hanviet:"phụ trách",   example_zh:"他很负责任。",         example_pinyin:"Tā hěn fùzérèn.",             example_vi:"Anh ấy rất có trách nhiệm.", hsk:3},
  {hanzi:"积极", pinyin:"jījí",     tone:"1-2", meaning_vi:"tích cực, hăng hái", hanviet:"tích cực",    example_zh:"她很积极。",           example_pinyin:"Tā hěn jījí.",                example_vi:"Cô ấy rất tích cực.", hsk:3},
  // ── Danh từ (nouns) ──
  {hanzi:"爱好", pinyin:"àihào",    tone:"4-4", meaning_vi:"sở thích",           hanviet:"ái hảo",      example_zh:"我的爱好是音乐。",     example_pinyin:"Wǒ de àihào shì yīnyuè.",     example_vi:"Sở thích của tôi là âm nhạc.", hsk:3},
  {hanzi:"变化", pinyin:"biànhuà",  tone:"4-4", meaning_vi:"thay đổi, biến hóa", hanviet:"biến hóa",    example_zh:"城市变化很大。",       example_pinyin:"Chéngshì biànhuà hěn dà.",    example_vi:"Thành phố thay đổi rất nhiều.", hsk:3},
  {hanzi:"感情", pinyin:"gǎnqíng",  tone:"3-2", meaning_vi:"cảm xúc, tình cảm",  hanviet:"cảm tình",    example_zh:"朋友之间有感情。",     example_pinyin:"Péngyǒu zhī jiān yǒu gǎnqíng.", example_vi:"Giữa bạn bè có tình cảm.", hsk:3},
  {hanzi:"机会", pinyin:"jīhuì",    tone:"1-4", meaning_vi:"cơ hội",             hanviet:"cơ hội",      example_zh:"抓住机会。",           example_pinyin:"Zhuā zhù jīhuì.",             example_vi:"Nắm lấy cơ hội.", hsk:3},
  {hanzi:"关系", pinyin:"guānxi",   tone:"1-0", meaning_vi:"quan hệ, mối liên hệ",hanviet:"quan hệ",    example_zh:"我们关系很好。",       example_pinyin:"Wǒmen guānxi hěn hǎo.",       example_vi:"Mối quan hệ của chúng tôi rất tốt.", hsk:3},
  {hanzi:"环境", pinyin:"huánjìng", tone:"2-4", meaning_vi:"môi trường",         hanviet:"hoàn cảnh",   example_zh:"保护环境。",           example_pinyin:"Bǎohù huánjìng.",             example_vi:"Bảo vệ môi trường.", hsk:3},
  {hanzi:"历史", pinyin:"lìshǐ",    tone:"4-3", meaning_vi:"lịch sử",            hanviet:"lịch sử",     example_zh:"中国历史很悠久。",     example_pinyin:"Zhōngguó lìshǐ hěn yōujiǔ.",  example_vi:"Lịch sử Trung Quốc rất lâu đời.", hsk:3},
  {hanzi:"目的", pinyin:"mùdì",     tone:"4-4", meaning_vi:"mục đích",           hanviet:"mục đích",    example_zh:"我的目的是学好汉语。", example_pinyin:"Wǒ de mùdì shì xuéhǎo Hànyǔ.", example_vi:"Mục đích của tôi là học tốt tiếng Trung.", hsk:3},
  {hanzi:"情况", pinyin:"qíngkuàng",tone:"2-4", meaning_vi:"tình hình, hoàn cảnh",hanviet:"tình huống", example_zh:"情况怎么样？",        example_pinyin:"Qíngkuàng zěnme yàng?",        example_vi:"Tình hình như thế nào?", hsk:3},
  {hanzi:"社会", pinyin:"shèhuì",   tone:"4-4", meaning_vi:"xã hội",             hanviet:"xã hội",      example_zh:"社会在进步。",         example_pinyin:"Shèhuì zài jìnbù.",           example_vi:"Xã hội đang tiến bộ.", hsk:3},
  {hanzi:"文化", pinyin:"wénhuà",   tone:"2-4", meaning_vi:"văn hóa",            hanviet:"văn hóa",     example_zh:"中国文化很有趣。",     example_pinyin:"Zhōngguó wénhuà hěn yǒuqù.",  example_vi:"Văn hóa Trung Quốc rất thú vị.", hsk:3},
  {hanzi:"原因", pinyin:"yuányīn",  tone:"2-1", meaning_vi:"nguyên nhân, lý do", hanviet:"nguyên nhân", example_zh:"原因是什么？",         example_pinyin:"Yuányīn shì shénme?",         example_vi:"Nguyên nhân là gì?", hsk:3},
  {hanzi:"方面", pinyin:"fāngmiàn", tone:"1-4", meaning_vi:"phương diện, khía cạnh",hanviet:"phương diện", example_zh:"各方面都很好。",    example_pinyin:"Gè fāngmiàn dōu hěn hǎo.",   example_vi:"Mọi phương diện đều rất tốt.", hsk:3},
  {hanzi:"结果", pinyin:"jiéguǒ",   tone:"2-3", meaning_vi:"kết quả",            hanviet:"kết quả",     example_zh:"考试结果出来了。",     example_pinyin:"Kǎoshì jiéguǒ chūlái le.",    example_vi:"Kết quả thi đã ra.", hsk:3},
  {hanzi:"部分", pinyin:"bùfen",    tone:"4-0", meaning_vi:"bộ phận, một phần",  hanviet:"bộ phận",     example_zh:"一部分人同意。",       example_pinyin:"Yī bùfen rén tóngyì.",         example_vi:"Một bộ phận người đồng ý.", hsk:3},
  // ── Phó từ / Liên từ ──
  {hanzi:"但是", pinyin:"dànshì",   tone:"4-4", meaning_vi:"nhưng, nhưng mà",    hanviet:"đản thị",     example_zh:"喜欢，但是太贵了。",   example_pinyin:"Xǐhuān, dànshì tài guì le.",  example_vi:"Thích, nhưng quá đắt.", hsk:3},
  {hanzi:"所以", pinyin:"suǒyǐ",    tone:"3-3", meaning_vi:"vì vậy, do đó",      hanviet:"sở dĩ",       example_zh:"因为下雨，所以没去。", example_pinyin:"Yīnwèi xià yǔ, suǒyǐ méi qù.", example_vi:"Vì trời mưa nên không đi.", hsk:3},
  {hanzi:"根据", pinyin:"gēnjù",    tone:"1-4", meaning_vi:"căn cứ, dựa theo",   hanviet:"căn cứ",      example_zh:"根据天气预报…",       example_pinyin:"Gēnjù tiānqì yùbào…",         example_vi:"Dựa theo dự báo thời tiết…", hsk:3},
  {hanzi:"几乎", pinyin:"jīhū",     tone:"1-1", meaning_vi:"gần như, hầu như",   hanviet:"cơ hồ",       example_zh:"几乎每天都来。",       example_pinyin:"Jīhū měitiān dōu lái.",        example_vi:"Gần như ngày nào cũng đến.", hsk:3},
  {hanzi:"总是", pinyin:"zǒngshì",  tone:"3-4", meaning_vi:"luôn luôn, bao giờ cũng",hanviet:"tổng thị", example_zh:"他总是迟到。",        example_pinyin:"Tā zǒngshì chídào.",           example_vi:"Anh ấy luôn luôn đến muộn.", hsk:3},
];
