// ══════════════════════════════════════════
// KOERU Pinyin Speed — HSK 1 Data
// 100 từ HSK 1 chuẩn, đủ: hanzi, pinyin, tone, nghĩa Việt, Hán Việt, ví dụ
// ══════════════════════════════════════════
const HSK1_DATA = [
  // ── Đại từ ──
  {hanzi:"我",    pinyin:"wǒ",      tone:3, meaning_vi:"tôi, mình",        hanviet:"ngã",       example_zh:"我是学生",    example_pinyin:"Wǒ shì xuésheng",   example_vi:"Tôi là học sinh"},
  {hanzi:"你",    pinyin:"nǐ",      tone:3, meaning_vi:"bạn, anh/chị",     hanviet:"nhĩ",       example_zh:"你好",        example_pinyin:"Nǐ hǎo",             example_vi:"Xin chào"},
  {hanzi:"他",    pinyin:"tā",      tone:1, meaning_vi:"anh ấy, ông ấy",   hanviet:"tha",       example_zh:"他是老师",    example_pinyin:"Tā shì lǎoshī",      example_vi:"Anh ấy là giáo viên"},
  {hanzi:"她",    pinyin:"tā",      tone:1, meaning_vi:"cô ấy, chị ấy",    hanviet:"tha (nữ)",  example_zh:"她很漂亮",    example_pinyin:"Tā hěn piàoliang",   example_vi:"Cô ấy rất đẹp"},
  {hanzi:"我们",  pinyin:"wǒmen",   tone:3, meaning_vi:"chúng tôi",        hanviet:"ngã môn",   example_zh:"我们是朋友",  example_pinyin:"Wǒmen shì péngyǒu", example_vi:"Chúng tôi là bạn bè"},
  {hanzi:"你们",  pinyin:"nǐmen",   tone:3, meaning_vi:"các bạn",          hanviet:"nhĩ môn",   example_zh:"你们好",      example_pinyin:"Nǐmen hǎo",          example_vi:"Xin chào các bạn"},
  {hanzi:"他们",  pinyin:"tāmen",   tone:1, meaning_vi:"họ (nam/chung)",    hanviet:"tha môn",   example_zh:"他们是学生",  example_pinyin:"Tāmen shì xuésheng", example_vi:"Họ là học sinh"},

  // ── Chào hỏi & lịch sự ──
  {hanzi:"你好",   pinyin:"nǐ hǎo",    tone:3, meaning_vi:"xin chào",       hanviet:"nhĩ hảo",     example_zh:"你好！",       example_pinyin:"Nǐ hǎo!",            example_vi:"Xin chào!"},
  {hanzi:"谢谢",   pinyin:"xièxie",    tone:4, meaning_vi:"cảm ơn",         hanviet:"tạ tạ",       example_zh:"谢谢你",       example_pinyin:"Xièxie nǐ",          example_vi:"Cảm ơn bạn"},
  {hanzi:"对不起", pinyin:"duìbuqǐ",   tone:4, meaning_vi:"xin lỗi",        hanviet:"đối bất khởi",example_zh:"对不起！",     example_pinyin:"Duìbuqǐ!",           example_vi:"Xin lỗi!"},
  {hanzi:"没关系", pinyin:"méiguānxi", tone:2, meaning_vi:"không sao",       hanviet:"một quan hệ", example_zh:"没关系！",     example_pinyin:"Méiguānxi!",         example_vi:"Không sao!"},
  {hanzi:"再见",   pinyin:"zàijiàn",   tone:4, meaning_vi:"tạm biệt",        hanviet:"tái kiến",    example_zh:"明天再见",     example_pinyin:"Míngtiān zàijiàn",   example_vi:"Hẹn gặp lại ngày mai"},
  {hanzi:"请",     pinyin:"qǐng",      tone:3, meaning_vi:"xin, mời",        hanviet:"thỉnh",       example_zh:"请进",         example_pinyin:"Qǐng jìn",           example_vi:"Xin mời vào"},
  {hanzi:"不客气", pinyin:"bù kèqi",   tone:4, meaning_vi:"không có gì",     hanviet:"bất khách khí",example_zh:"不客气！",    example_pinyin:"Bù kèqi!",           example_vi:"Không có gì!"},

  // ── Số đếm ──
  {hanzi:"一", pinyin:"yī",   tone:1, meaning_vi:"một (1)",         hanviet:"nhất",  example_zh:"一个苹果", example_pinyin:"Yī gè píngguǒ",  example_vi:"Một quả táo"},
  {hanzi:"二", pinyin:"èr",   tone:4, meaning_vi:"hai (2)",         hanviet:"nhị",   example_zh:"二十",     example_pinyin:"Èrshí",           example_vi:"Hai mươi"},
  {hanzi:"三", pinyin:"sān",  tone:1, meaning_vi:"ba (3)",          hanviet:"tam",   example_zh:"三个人",   example_pinyin:"Sān gè rén",      example_vi:"Ba người"},
  {hanzi:"四", pinyin:"sì",   tone:4, meaning_vi:"bốn (4)",         hanviet:"tứ",    example_zh:"四月",     example_pinyin:"Sì yuè",          example_vi:"Tháng Tư"},
  {hanzi:"五", pinyin:"wǔ",   tone:3, meaning_vi:"năm (5)",         hanviet:"ngũ",   example_zh:"五岁",     example_pinyin:"Wǔ suì",          example_vi:"Năm tuổi"},
  {hanzi:"六", pinyin:"liù",  tone:4, meaning_vi:"sáu (6)",         hanviet:"lục",   example_zh:"六月",     example_pinyin:"Liù yuè",         example_vi:"Tháng Sáu"},
  {hanzi:"七", pinyin:"qī",   tone:1, meaning_vi:"bảy (7)",         hanviet:"thất",  example_zh:"七天",     example_pinyin:"Qī tiān",         example_vi:"Bảy ngày"},
  {hanzi:"八", pinyin:"bā",   tone:1, meaning_vi:"tám (8)",         hanviet:"bát",   example_zh:"八月",     example_pinyin:"Bā yuè",          example_vi:"Tháng Tám"},
  {hanzi:"九", pinyin:"jiǔ",  tone:3, meaning_vi:"chín (9)",        hanviet:"cửu",   example_zh:"九点",     example_pinyin:"Jiǔ diǎn",        example_vi:"Chín giờ"},
  {hanzi:"十", pinyin:"shí",  tone:2, meaning_vi:"mười (10)",       hanviet:"thập",  example_zh:"十块钱",   example_pinyin:"Shí kuài qián",   example_vi:"Mười tệ"},
  {hanzi:"百", pinyin:"bǎi",  tone:3, meaning_vi:"trăm",            hanviet:"bách",  example_zh:"一百块",   example_pinyin:"Yī bǎi kuài",     example_vi:"Một trăm tệ"},
  {hanzi:"零", pinyin:"líng", tone:2, meaning_vi:"không (0)",        hanviet:"linh",  example_zh:"零度",     example_pinyin:"Líng dù",         example_vi:"Không độ"},
  {hanzi:"两", pinyin:"liǎng",tone:3, meaning_vi:"hai (trước danh từ)", hanviet:"lưỡng", example_zh:"两个人", example_pinyin:"Liǎng gè rén", example_vi:"Hai người"},

  // ── Thời gian ──
  {hanzi:"今天", pinyin:"jīntiān",  tone:1, meaning_vi:"hôm nay",           hanviet:"kim thiên",  example_zh:"今天天气好",   example_pinyin:"Jīntiān tiānqì hǎo", example_vi:"Hôm nay thời tiết đẹp"},
  {hanzi:"明天", pinyin:"míngtiān", tone:2, meaning_vi:"ngày mai",           hanviet:"minh thiên", example_zh:"明天见",       example_pinyin:"Míngtiān jiàn",      example_vi:"Hẹn gặp ngày mai"},
  {hanzi:"昨天", pinyin:"zuótiān",  tone:2, meaning_vi:"hôm qua",            hanviet:"tạc thiên",  example_zh:"昨天很冷",     example_pinyin:"Zuótiān hěn lěng",   example_vi:"Hôm qua rất lạnh"},
  {hanzi:"年",   pinyin:"nián",     tone:2, meaning_vi:"năm (year)",         hanviet:"niên",       example_zh:"今年",         example_pinyin:"Jīnnián",            example_vi:"Năm nay"},
  {hanzi:"月",   pinyin:"yuè",      tone:4, meaning_vi:"tháng, mặt trăng",  hanviet:"nguyệt",     example_zh:"一月",         example_pinyin:"Yī yuè",             example_vi:"Tháng Một"},
  {hanzi:"日",   pinyin:"rì",       tone:4, meaning_vi:"ngày, mặt trời",    hanviet:"nhật",       example_zh:"三月八日",     example_pinyin:"Sān yuè bā rì",      example_vi:"Ngày 8/3"},
  {hanzi:"上午", pinyin:"shàngwǔ",  tone:4, meaning_vi:"buổi sáng (trước trưa)", hanviet:"thượng ngọ", example_zh:"上午十点", example_pinyin:"Shàngwǔ shí diǎn", example_vi:"10 giờ sáng"},
  {hanzi:"下午", pinyin:"xiàwǔ",    tone:4, meaning_vi:"buổi chiều",         hanviet:"hạ ngọ",     example_zh:"下午三点",     example_pinyin:"Xiàwǔ sān diǎn",     example_vi:"3 giờ chiều"},
  {hanzi:"现在", pinyin:"xiànzài",  tone:4, meaning_vi:"bây giờ, hiện tại", hanviet:"hiện tại",   example_zh:"现在几点？",   example_pinyin:"Xiànzài jǐ diǎn?",   example_vi:"Bây giờ mấy giờ?"},
  {hanzi:"时候", pinyin:"shíhou",   tone:2, meaning_vi:"lúc, khi",           hanviet:"thời hầu",   example_zh:"什么时候？",   example_pinyin:"Shénme shíhou?",     example_vi:"Khi nào?"},

  // ── Con người & gia đình ──
  {hanzi:"人",   pinyin:"rén",     tone:2, meaning_vi:"người",              hanviet:"nhân",      example_zh:"中国人",    example_pinyin:"Zhōngguó rén",    example_vi:"Người Trung Quốc"},
  {hanzi:"朋友", pinyin:"péngyǒu", tone:2, meaning_vi:"bạn bè",            hanviet:"bằng hữu",  example_zh:"好朋友",    example_pinyin:"Hǎo péngyǒu",    example_vi:"Bạn tốt"},
  {hanzi:"老师", pinyin:"lǎoshī",  tone:3, meaning_vi:"giáo viên, thầy/cô",hanviet:"lão sư",    example_zh:"老师好！",  example_pinyin:"Lǎoshī hǎo!",    example_vi:"Chào thầy/cô!"},
  {hanzi:"学生", pinyin:"xuésheng",tone:2, meaning_vi:"học sinh",           hanviet:"học sinh",  example_zh:"我是学生",  example_pinyin:"Wǒ shì xuésheng",example_vi:"Tôi là học sinh"},
  {hanzi:"医生", pinyin:"yīshēng", tone:1, meaning_vi:"bác sĩ",             hanviet:"y sinh",    example_zh:"他是医生",  example_pinyin:"Tā shì yīshēng",  example_vi:"Anh ấy là bác sĩ"},
  {hanzi:"妈妈", pinyin:"māma",    tone:1, meaning_vi:"mẹ",                 hanviet:"ma ma",     example_zh:"妈妈在家",  example_pinyin:"Māma zài jiā",    example_vi:"Mẹ ở nhà"},
  {hanzi:"爸爸", pinyin:"bàba",    tone:4, meaning_vi:"bố, ba",             hanviet:"ba ba",     example_zh:"爸爸很忙",  example_pinyin:"Bàba hěn máng",   example_vi:"Bố rất bận"},
  {hanzi:"儿子", pinyin:"érzi",    tone:2, meaning_vi:"con trai",           hanviet:"nhi tử",    example_zh:"我的儿子",  example_pinyin:"Wǒ de érzi",      example_vi:"Con trai tôi"},
  {hanzi:"女儿", pinyin:"nǚ'ér",   tone:3, meaning_vi:"con gái",            hanviet:"nữ nhi",    example_zh:"她的女儿",  example_pinyin:"Tā de nǚ'ér",     example_vi:"Con gái của cô ấy"},

  // ── Động từ ──
  {hanzi:"吃",   pinyin:"chī",     tone:1, meaning_vi:"ăn",                 hanviet:"ngật",      example_zh:"吃饭",      example_pinyin:"Chī fàn",         example_vi:"Ăn cơm"},
  {hanzi:"喝",   pinyin:"hē",      tone:1, meaning_vi:"uống",               hanviet:"hát",       example_zh:"喝水",      example_pinyin:"Hē shuǐ",         example_vi:"Uống nước"},
  {hanzi:"看",   pinyin:"kàn",     tone:4, meaning_vi:"xem, nhìn, đọc",    hanviet:"khán",      example_zh:"看书",      example_pinyin:"Kàn shū",         example_vi:"Đọc sách"},
  {hanzi:"听",   pinyin:"tīng",    tone:1, meaning_vi:"nghe",               hanviet:"thính",     example_zh:"听音乐",    example_pinyin:"Tīng yīnyuè",     example_vi:"Nghe nhạc"},
  {hanzi:"说",   pinyin:"shuō",    tone:1, meaning_vi:"nói",                hanviet:"thuyết",    example_zh:"说汉语",    example_pinyin:"Shuō Hànyǔ",      example_vi:"Nói tiếng Trung"},
  {hanzi:"来",   pinyin:"lái",     tone:2, meaning_vi:"đến, lại",           hanviet:"lai",       example_zh:"来吧",      example_pinyin:"Lái ba",          example_vi:"Đến đây đi"},
  {hanzi:"去",   pinyin:"qù",      tone:4, meaning_vi:"đi, rời",            hanviet:"khứ",       example_zh:"去学校",    example_pinyin:"Qù xuéxiào",      example_vi:"Đi học"},
  {hanzi:"买",   pinyin:"mǎi",     tone:3, meaning_vi:"mua",                hanviet:"mãi",       example_zh:"买东西",    example_pinyin:"Mǎi dōngxi",      example_vi:"Mua đồ"},
  {hanzi:"有",   pinyin:"yǒu",     tone:3, meaning_vi:"có",                 hanviet:"hữu",       example_zh:"我有猫",    example_pinyin:"Wǒ yǒu māo",      example_vi:"Tôi có mèo"},
  {hanzi:"是",   pinyin:"shì",     tone:4, meaning_vi:"là (động từ)",       hanviet:"thị",       example_zh:"我是学生",  example_pinyin:"Wǒ shì xuésheng",example_vi:"Tôi là học sinh"},
  {hanzi:"在",   pinyin:"zài",     tone:4, meaning_vi:"ở, đang (ở tại)",   hanviet:"tại",       example_zh:"我在家",    example_pinyin:"Wǒ zài jiā",      example_vi:"Tôi ở nhà"},
  {hanzi:"工作", pinyin:"gōngzuò", tone:1, meaning_vi:"làm việc, công việc",hanviet:"công tác",  example_zh:"你工作吗？",example_pinyin:"Nǐ gōngzuò ma?", example_vi:"Bạn đi làm không?"},
  {hanzi:"学习", pinyin:"xuéxí",   tone:2, meaning_vi:"học tập",            hanviet:"học tập",   example_zh:"学习汉语",  example_pinyin:"Xuéxí Hànyǔ",     example_vi:"Học tiếng Trung"},
  {hanzi:"睡觉", pinyin:"shuìjiào",tone:4, meaning_vi:"ngủ",                hanviet:"thụy giác", example_zh:"几点睡觉？",example_pinyin:"Jǐ diǎn shuìjiào?",example_vi:"Mấy giờ đi ngủ?"},
  {hanzi:"喜欢", pinyin:"xǐhuān",  tone:3, meaning_vi:"thích",              hanviet:"hỉ hoan",   example_zh:"我喜欢猫",  example_pinyin:"Wǒ xǐhuān māo",   example_vi:"Tôi thích mèo"},
  {hanzi:"认识", pinyin:"rènshi",  tone:4, meaning_vi:"quen biết, nhận ra", hanviet:"nhận thức", example_zh:"很高兴认识你",example_pinyin:"Hěn gāoxìng rènshi nǐ",example_vi:"Rất vui được biết bạn"},
  {hanzi:"叫",   pinyin:"jiào",    tone:4, meaning_vi:"gọi là, tên là",     hanviet:"khiếu",     example_zh:"你叫什么名字？",example_pinyin:"Nǐ jiào shénme míngzi?",example_vi:"Bạn tên là gì?"},
  {hanzi:"想",   pinyin:"xiǎng",   tone:3, meaning_vi:"muốn, nghĩ",         hanviet:"tưởng",     example_zh:"我想去",    example_pinyin:"Wǒ xiǎng qù",     example_vi:"Tôi muốn đi"},
  {hanzi:"回",   pinyin:"huí",     tone:2, meaning_vi:"quay về",            hanviet:"hồi",       example_zh:"回家",      example_pinyin:"Huí jiā",         example_vi:"Về nhà"},
  {hanzi:"开",   pinyin:"kāi",     tone:1, meaning_vi:"mở, lái (xe)",       hanviet:"khai",      example_zh:"开门",      example_pinyin:"Kāi mén",         example_vi:"Mở cửa"},
  {hanzi:"坐",   pinyin:"zuò",     tone:4, meaning_vi:"ngồi, đi (phương tiện)",hanviet:"tọa",    example_zh:"请坐",      example_pinyin:"Qǐng zuò",        example_vi:"Mời ngồi"},
  {hanzi:"住",   pinyin:"zhù",     tone:4, meaning_vi:"ở, sống tại",        hanviet:"trú",       example_zh:"你住哪儿？",example_pinyin:"Nǐ zhù nǎr?",    example_vi:"Bạn ở đâu?"},

  // ── Tính từ / Trạng từ ──
  {hanzi:"好",   pinyin:"hǎo",     tone:3, meaning_vi:"tốt, ổn, được",     hanviet:"hảo",       example_zh:"好的",      example_pinyin:"Hǎo de",          example_vi:"Được rồi"},
  {hanzi:"大",   pinyin:"dà",      tone:4, meaning_vi:"lớn, to",           hanviet:"đại",       example_zh:"大学",      example_pinyin:"Dàxué",           example_vi:"Đại học"},
  {hanzi:"小",   pinyin:"xiǎo",    tone:3, meaning_vi:"nhỏ, bé",           hanviet:"tiểu",      example_zh:"小猫",      example_pinyin:"Xiǎo māo",        example_vi:"Mèo nhỏ"},
  {hanzi:"多",   pinyin:"duō",     tone:1, meaning_vi:"nhiều",             hanviet:"đa",        example_zh:"很多人",    example_pinyin:"Hěn duō rén",     example_vi:"Rất nhiều người"},
  {hanzi:"少",   pinyin:"shǎo",    tone:3, meaning_vi:"ít",                hanviet:"thiểu",     example_zh:"人很少",    example_pinyin:"Rén hěn shǎo",    example_vi:"Người rất ít"},
  {hanzi:"高",   pinyin:"gāo",     tone:1, meaning_vi:"cao",               hanviet:"cao",       example_zh:"他很高",    example_pinyin:"Tā hěn gāo",      example_vi:"Anh ấy rất cao"},
  {hanzi:"热",   pinyin:"rè",      tone:4, meaning_vi:"nóng",              hanviet:"nhiệt",     example_zh:"天气很热",  example_pinyin:"Tiānqì hěn rè",   example_vi:"Thời tiết rất nóng"},
  {hanzi:"冷",   pinyin:"lěng",    tone:3, meaning_vi:"lạnh",              hanviet:"lãnh",      example_zh:"今天很冷",  example_pinyin:"Jīntiān hěn lěng",example_vi:"Hôm nay rất lạnh"},
  {hanzi:"漂亮", pinyin:"piàoliang",tone:4, meaning_vi:"đẹp (ngoại hình)", hanviet:"phiêu lượng",example_zh:"她很漂亮", example_pinyin:"Tā hěn piàoliang",example_vi:"Cô ấy rất đẹp"},
  {hanzi:"忙",   pinyin:"máng",    tone:2, meaning_vi:"bận rộn",           hanviet:"mang",      example_zh:"我很忙",    example_pinyin:"Wǒ hěn máng",     example_vi:"Tôi rất bận"},
  {hanzi:"累",   pinyin:"lèi",     tone:4, meaning_vi:"mệt mỏi",           hanviet:"lụy",       example_zh:"我很累",    example_pinyin:"Wǒ hěn lèi",      example_vi:"Tôi rất mệt"},
  {hanzi:"很",   pinyin:"hěn",     tone:3, meaning_vi:"rất",               hanviet:"ngận",      example_zh:"很好",      example_pinyin:"Hěn hǎo",         example_vi:"Rất tốt"},
  {hanzi:"太",   pinyin:"tài",     tone:4, meaning_vi:"quá, rất (cảm thán)",hanviet:"thái",     example_zh:"太好了！",  example_pinyin:"Tài hǎo le!",     example_vi:"Tuyệt vời quá!"},
  {hanzi:"也",   pinyin:"yě",      tone:3, meaning_vi:"cũng",              hanviet:"dã",        example_zh:"我也是",    example_pinyin:"Wǒ yě shì",       example_vi:"Tôi cũng vậy"},
  {hanzi:"都",   pinyin:"dōu",     tone:1, meaning_vi:"đều, tất cả",       hanviet:"đô",        example_zh:"都好",      example_pinyin:"Dōu hǎo",         example_vi:"Đều tốt cả"},
  {hanzi:"不",   pinyin:"bù",      tone:4, meaning_vi:"không (phủ định)",  hanviet:"bất",       example_zh:"不好",      example_pinyin:"Bù hǎo",          example_vi:"Không tốt"},
  {hanzi:"没",   pinyin:"méi",     tone:2, meaning_vi:"không có, chưa",    hanviet:"một",       example_zh:"没有",      example_pinyin:"Méiyǒu",          example_vi:"Không có"},

  // ── Đồ ăn & đồ vật ──
  {hanzi:"饭",   pinyin:"fàn",     tone:4, meaning_vi:"cơm, bữa ăn",       hanviet:"phạn",      example_zh:"吃饭",      example_pinyin:"Chī fàn",         example_vi:"Ăn cơm"},
  {hanzi:"水",   pinyin:"shuǐ",    tone:3, meaning_vi:"nước",               hanviet:"thủy",      example_zh:"喝水",      example_pinyin:"Hē shuǐ",         example_vi:"Uống nước"},
  {hanzi:"茶",   pinyin:"chá",     tone:2, meaning_vi:"trà",                hanviet:"trà",       example_zh:"喝茶",      example_pinyin:"Hē chá",          example_vi:"Uống trà"},
  {hanzi:"苹果", pinyin:"píngguǒ", tone:2, meaning_vi:"quả táo",            hanviet:"bình quả",  example_zh:"一个苹果",  example_pinyin:"Yī gè píngguǒ",  example_vi:"Một quả táo"},
  {hanzi:"米饭", pinyin:"mǐfàn",   tone:3, meaning_vi:"cơm gạo",            hanviet:"mễ phạn",   example_zh:"我要米饭",  example_pinyin:"Wǒ yào mǐfàn",   example_vi:"Tôi muốn cơm"},
  {hanzi:"书",   pinyin:"shū",     tone:1, meaning_vi:"sách",               hanviet:"thư",       example_zh:"看书",      example_pinyin:"Kàn shū",         example_vi:"Đọc sách"},
  {hanzi:"钱",   pinyin:"qián",    tone:2, meaning_vi:"tiền",               hanviet:"tiền",      example_zh:"多少钱？",  example_pinyin:"Duōshao qián?",   example_vi:"Bao nhiêu tiền?"},
  {hanzi:"猫",   pinyin:"māo",     tone:1, meaning_vi:"mèo",                hanviet:"miêu",      example_zh:"小猫",      example_pinyin:"Xiǎo māo",        example_vi:"Mèo nhỏ"},
  {hanzi:"狗",   pinyin:"gǒu",     tone:3, meaning_vi:"chó",                hanviet:"cẩu",       example_zh:"大狗",      example_pinyin:"Dà gǒu",          example_vi:"Chó lớn"},
  {hanzi:"电话", pinyin:"diànhuà", tone:4, meaning_vi:"điện thoại",          hanviet:"điện thoại",example_zh:"打电话",    example_pinyin:"Dǎ diànhuà",      example_vi:"Gọi điện"},
  {hanzi:"电脑", pinyin:"diànnǎo", tone:4, meaning_vi:"máy tính",            hanviet:"điện não",  example_zh:"用电脑",    example_pinyin:"Yòng diànnǎo",    example_vi:"Dùng máy tính"},

  // ── Nơi chốn ──
  {hanzi:"家",   pinyin:"jiā",     tone:1, meaning_vi:"nhà, gia đình",      hanviet:"gia",       example_zh:"回家",      example_pinyin:"Huí jiā",         example_vi:"Về nhà"},
  {hanzi:"学校", pinyin:"xuéxiào", tone:2, meaning_vi:"trường học",          hanviet:"học hiệu",  example_zh:"去学校",    example_pinyin:"Qù xuéxiào",      example_vi:"Đi học"},
  {hanzi:"医院", pinyin:"yīyuàn",  tone:1, meaning_vi:"bệnh viện",           hanviet:"y viện",    example_zh:"去医院",    example_pinyin:"Qù yīyuàn",       example_vi:"Đi bệnh viện"},
  {hanzi:"中国", pinyin:"Zhōngguó",tone:1, meaning_vi:"Trung Quốc",          hanviet:"Trung Quốc",example_zh:"我来自中国",example_pinyin:"Wǒ láizì Zhōngguó",example_vi:"Tôi đến từ Trung Quốc"},
  {hanzi:"北京", pinyin:"Běijīng", tone:3, meaning_vi:"Bắc Kinh",            hanviet:"Bắc Kinh",  example_zh:"北京很大",  example_pinyin:"Běijīng hěn dà",  example_vi:"Bắc Kinh rất rộng"},

  // ── Câu hỏi ──
  {hanzi:"什么", pinyin:"shénme",  tone:2, meaning_vi:"cái gì, gì",         hanviet:"thập ma",   example_zh:"这是什么？",example_pinyin:"Zhè shì shénme?", example_vi:"Đây là gì?"},
  {hanzi:"哪儿", pinyin:"nǎr",     tone:3, meaning_vi:"ở đâu",              hanviet:"na nhị",    example_zh:"你在哪儿？",example_pinyin:"Nǐ zài nǎr?",    example_vi:"Bạn ở đâu?"},
  {hanzi:"谁",   pinyin:"shéi",    tone:2, meaning_vi:"ai",                 hanviet:"thuỳ",      example_zh:"他是谁？",  example_pinyin:"Tā shì shéi?",    example_vi:"Anh ấy là ai?"},
  {hanzi:"几",   pinyin:"jǐ",      tone:3, meaning_vi:"mấy (dưới 10)",      hanviet:"kỉ",        example_zh:"几点了？",  example_pinyin:"Jǐ diǎn le?",     example_vi:"Mấy giờ rồi?"},
  {hanzi:"多少", pinyin:"duōshao", tone:1, meaning_vi:"bao nhiêu",           hanviet:"đa thiểu",  example_zh:"多少钱？",  example_pinyin:"Duōshao qián?",   example_vi:"Bao nhiêu tiền?"},
  {hanzi:"怎么", pinyin:"zěnme",   tone:3, meaning_vi:"làm thế nào, sao",   hanviet:"chẩm ma",   example_zh:"怎么去？",  example_pinyin:"Zěnme qù?",       example_vi:"Đi thế nào?"},
  {hanzi:"哪",   pinyin:"nǎ",      tone:3, meaning_vi:"cái nào, ở đâu",     hanviet:"na",        example_zh:"哪个？",    example_pinyin:"Nǎ gè?",          example_vi:"Cái nào?"},

  // ── Khác ──
  {hanzi:"的",   pinyin:"de",      tone:0, meaning_vi:"của (trợ từ sở hữu)",hanviet:"đích",      example_zh:"我的书",    example_pinyin:"Wǒ de shū",       example_vi:"Sách của tôi"},
  {hanzi:"了",   pinyin:"le",      tone:0, meaning_vi:"rồi (trợ từ hoàn thành)",hanviet:"liễu",  example_zh:"吃了",      example_pinyin:"Chī le",          example_vi:"Ăn rồi"},
  {hanzi:"吗",   pinyin:"ma",      tone:0, meaning_vi:"không? (trợ từ hỏi yes/no)",hanviet:"mạ", example_zh:"好吗？",    example_pinyin:"Hǎo ma?",         example_vi:"Ổn không?"},
  {hanzi:"天气", pinyin:"tiānqì",  tone:1, meaning_vi:"thời tiết",           hanviet:"thiên khí", example_zh:"今天天气好",example_pinyin:"Jīntiān tiānqì hǎo",example_vi:"Hôm nay thời tiết đẹp"},
  {hanzi:"汉语", pinyin:"Hànyǔ",   tone:4, meaning_vi:"tiếng Trung (Hán ngữ)", hanviet:"Hán ngữ", example_zh:"学汉语",  example_pinyin:"Xué Hànyǔ",       example_vi:"Học tiếng Trung"},
  {hanzi:"名字", pinyin:"míngzi",  tone:2, meaning_vi:"tên",                 hanviet:"danh tự",   example_zh:"你叫什么名字？",example_pinyin:"Nǐ jiào shénme míngzi?",example_vi:"Bạn tên là gì?"},
  {hanzi:"这",   pinyin:"zhè",     tone:4, meaning_vi:"này, đây",            hanviet:"giá",       example_zh:"这是什么？",example_pinyin:"Zhè shì shénme?", example_vi:"Đây là gì?"},
  {hanzi:"那",   pinyin:"nà",      tone:4, meaning_vi:"kia, đó",             hanviet:"na",        example_zh:"那是谁？",  example_pinyin:"Nà shì shéi?",    example_vi:"Kia là ai?"},
  {hanzi:"个",   pinyin:"gè",      tone:4, meaning_vi:"cái, người (lượng từ)",hanviet:"cá",       example_zh:"三个人",    example_pinyin:"Sān gè rén",      example_vi:"Ba người"},
];
