"""
fix_words_en.py — Dịch nghĩa tiếng Anh còn sót trong words[] của N3/N4
Chỉ fix các level N3/N4 (N1/N2 đã bị ẩn, N5 sạch rồi)
"""
import re
from pathlib import Path

JS = Path(__file__).parent.parent / "js"

# ── Translation dictionary ─────────────────────────────────────────────────
VI = {
    # N4
    "batting power": "sức đánh bóng",
    "(artificial) dialysis": "thẩm phân nhân tạo",
    "classmate": "bạn cùng lớp",
    "community chest": "quỹ từ thiện cộng đồng",
    "apprentice": "học việc; thợ học nghề",
    "cousin (male)": "anh/em họ (nam)",
    "base running": "chạy căn (bóng chày)",
    "racehorse": "ngựa đua",
    "primitive man": "người nguyên thủy",
    "(medical) specialist": "bác sĩ chuyên khoa",
    "anus": "hậu môn",
    "invitation": "lời mời; giấy mời",
    "commercial broadcasting": "phát thanh thương mại",
    "delivery": "giao hàng; vận chuyển",
    "direct delivery": "giao thẳng; vận chuyển trực tiếp",
    "black clothes": "áo đen; quần áo đen",
    "light metal": "kim loại nhẹ",
    "heat wave": "sóng nhiệt; nắng nóng gay gắt",
    "centrifuge": "máy ly tâm",
    "arhat": "La Hán (Phật giáo)",
    "entrance examination": "kỳ thi tuyển sinh",
    "perfect game": "trận đấu hoàn hảo",
    # N3
    "below freezing": "dưới 0 độ C; dưới điểm đóng băng",
    "glacier": "sông băng",
    "(building) stone": "đá xây dựng",
    "blood donation": "hiến máu",
    "blood pressure": "huyết áp",
    "acrobatics": "nhào lộn; xiếc",
    "arrangement": "dàn dựng; phối khí",
    "composer": "nhạc sĩ; nhà soạn nhạc",
    "erosion control": "chống xói mòn",
    "rejuvenation": "trẻ hóa; làm trẻ lại",
    "body": "cơ thể; thân thể",
    "body proportions": "tỷ lệ cơ thể",
    "egg yolk": "lòng đỏ trứng",
    "mountain stream": "suối núi",
    "complete translation": "bản dịch đầy đủ",
    "full employment": "toàn dụng lao động",
    "acute angle": "góc nhọn",
    "angle": "góc độ",
    "cornea": "giác mạc",
    "wishful": "hy vọng; mong muốn",
    "(relative) difficulty": "mức độ khó",
    "bottom price": "giá thấp nhất",
    "bottoming out": "chạm đáy",
    "(human) life": "cuộc sống; sinh mệnh",
    "resolute decision": "quyết định kiên quyết",
    "heroism": "chủ nghĩa anh hùng",
    "brave": "dũng cảm",
    "art exhibition": "triển lãm nghệ thuật",
    "beautiful face": "khuôn mặt đẹp",
    "beautiful voice": "giọng hát đẹp; giọng hay",
    "medicinal herb": "thảo dược; cây thuốc",
    "sao Kim": "sao Kim (Venus)",
    "carbohydrate": "carbohydrate; chất bột đường",
    "carbon (C)": "carbon (C)",
    "charcoal": "than củi; than hoa",
    "anatomy": "giải phẫu học",
    "clear explanation": "giải thích rõ ràng",
    "beloved wife": "vợ yêu dấu",
    "confinement": "giam cầm; hạn chế",
    "embargo": "cấm vận; lệnh cấm",
    "fuse": "cầu chì; ngòi nổ",
    "guidance": "hướng dẫn; chỉ đạo",
    "(vocal) volume": "âm lượng (giọng hát)",
    "aggregate amount": "tổng số tiền",
    "cold wave": "sóng lạnh; đợt lạnh",
    "decathlon": "mười môn phối hợp",
    "mating": "giao phối; bắt cặp",
    "negotiation": "đàm phán; thương lượng",
    "complexity": "sự phức tạp",
    "miscellaneous expenses": "chi phí linh tinh",
    "miscellaneous knowledge": "kiến thức tổng hợp",
    "addition": "phép cộng; thêm vào",
    "division": "phép chia; bộ phận",
    "adjournment": "hoãn phiên; giải tán tạm thời",
    "prose": "văn xuôi",
    "capital goods": "hàng tư liệu sản xuất",
    "consumer goods": "hàng tiêu dùng",
    "apology": "lời xin lỗi",
    "false charge": "tố cáo sai; vu khống",
    "(contained) within": "nằm trong; bao gồm trong",
    "re-election": "tái bầu cử",
    "reappointment": "tái bổ nhiệm",
    "embroidery": "thêu; đồ thêu",
    "gill net": "lưới đánh cá",
    "(judicial) precedent": "án lệ; tiền lệ tư pháp",
    "case": "vụ án; trường hợp",
    "(religious) festival": "lễ hội tôn giáo",
    "impoliteness": "sự vô lễ; thô lỗ",
    "headquarters": "trụ sở; bộ chỉ huy",
    "martial law": "thiết quân luật",
    "mountain path": "đường núi; lối mòn",
    "wages": "tiền lương; tiền công",
    "cholera": "bệnh tả",
    "anthropology": "nhân chủng học",
    "birds": "chim; các loài chim",
    "benign": "lành tính",
    "malignant": "ác tính",
    "tumor": "khối u",
    "cancer cell": "tế bào ung thư",
    "pediatrics": "khoa nhi; nhi khoa",
    "internal medicine": "nội khoa",
    "surgeon": "bác sĩ phẫu thuật",
    "operation": "phẫu thuật; vận hành",
    "incision": "vết mổ; vết cắt",
    "suture": "khâu vết thương",
    "anesthesia": "gây mê; gây tê",
    "pulse": "mạch đập",
    "symptom": "triệu chứng",
    "diagnosis": "chẩn đoán",
    "prognosis": "tiên lượng bệnh",
    "prescription": "đơn thuốc",
    "dose": "liều lượng",
    "side effect": "tác dụng phụ",
    "allergy": "dị ứng",
    "chronic": "mãn tính",
    "acute": "cấp tính",
    "contagious": "lây nhiễm",
    "infection": "nhiễm trùng; lây nhiễm",
    "antibiotics": "kháng sinh",
    "vaccine": "vắc-xin",
    "immune system": "hệ miễn dịch",
    "metabolism": "trao đổi chất",
    "hormone": "hormone",
    "enzyme": "enzyme",
    "protein": "protein; chất đạm",
    "vitamin": "vitamin",
    "mineral": "khoáng chất",
    "calcium": "canxi",
    "iron": "sắt (Fe)",
    "oxygen": "oxy",
    "nitrogen": "nitơ",
    "hydrogen": "hydro",
    "photosynthesis": "quang hợp",
    "evolution": "tiến hóa",
    "ecosystem": "hệ sinh thái",
    "species": "loài; chủng loài",
    "genus": "chi (phân loại sinh học)",
    "mammal": "động vật có vú",
    "reptile": "bò sát",
    "amphibian": "lưỡng cư",
    "insect": "côn trùng",
    "microbe": "vi khuẩn; vi sinh vật",
    "fungus": "nấm",
    "algae": "tảo",
    "fossil": "hóa thạch",
    "mineral deposit": "mỏ khoáng sản",
    "seismic wave": "sóng địa chấn",
    "tectonic plate": "mảng kiến tạo",
    "volcanic eruption": "phun trào núi lửa",
    "tsunami": "sóng thần",
    "typhoon": "bão nhiệt đới; cơn bão",
    "drought": "hạn hán",
    "flood": "lũ lụt",
    "landslide": "lở đất",
    "avalanche": "lở tuyết",
    "orbit": "quỹ đạo",
    "gravity": "trọng lực; hấp dẫn",
    "velocity": "vận tốc",
    "acceleration": "gia tốc",
    "momentum": "động lượng",
    "friction": "ma sát",
    "pressure": "áp suất",
    "density": "mật độ; khối lượng riêng",
    "wavelength": "bước sóng",
    "frequency": "tần số",
    "amplitude": "biên độ",
    "refraction": "khúc xạ",
    "reflection": "phản xạ",
    "diffraction": "nhiễu xạ",
    "conductor": "vật dẫn điện",
    "insulator": "vật cách điện",
    "semiconductor": "chất bán dẫn",
    "transistor": "transistor",
    "circuit": "mạch điện",
    "voltage": "điện áp",
    "current": "dòng điện",
    "resistance": "điện trở",
    "capacitor": "tụ điện",
    "inductor": "cuộn cảm",
    "algorithm": "thuật toán",
    "database": "cơ sở dữ liệu",
    "network": "mạng lưới",
    "protocol": "giao thức",
    "encryption": "mã hóa",
    "debugging": "gỡ lỗi",
    "interface": "giao diện",
    "software": "phần mềm",
    "hardware": "phần cứng",
    "operating system": "hệ điều hành",
    "browser": "trình duyệt",
    "server": "máy chủ",
    "client": "máy khách; khách hàng",
    "bandwidth": "băng thông",
    "latency": "độ trễ",
    "cache": "bộ nhớ đệm",
    "pixel": "điểm ảnh",
    "resolution": "độ phân giải",
    "format": "định dạng",
    "compress": "nén; nén dữ liệu",
    "backup": "sao lưu dự phòng",
    "log": "nhật ký; log",
    "debug": "gỡ lỗi",
    "syntax": "cú pháp",
    "variable": "biến số",
    "function": "hàm; chức năng",
    "loop": "vòng lặp",
    "array": "mảng",
    "object": "đối tượng",
    "class": "lớp; lớp học",
    "method": "phương thức; phương pháp",
    "parameter": "tham số",
    "argument": "đối số",
    "return value": "giá trị trả về",
    "error": "lỗi",
    "exception": "ngoại lệ",
    "null": "null; rỗng",
    "boolean": "kiểu boolean",
    "integer": "số nguyên",
    "float": "số thực; số dấu chấm động",
    "string": "chuỗi ký tự",
    "binary": "nhị phân",
    "hexadecimal": "thập lục phân",
    # More N3 specific
    # N3 batch 2
    "sao Kim (Venus)": "sao Kim (Venus)",
    "carbon (C)": "carbon (C)",
    "cholera": "bệnh tả",
    "anthropology": "nhân chủng học",
    "birds": "các loài chim",
    "benign": "lành tính",
    "conscience": "lương tâm",
    "bloodshed": "đổ máu; thảm sát",
    "abstemious": "điều độ; kiêng cữ",
    "antiproton": "phản proton",
    "positron": "positron (hạt dương điện tử)",
    "reception": "lễ tân; tiếp tân",
    "suspect": "nghi phạm; đáng ngờ",
    "another idea": "ý tưởng khác; suy nghĩ khác",
    "digression": "lạc đề; sự đi lạc chủ đề",
    "cho, ban": "cho; tặng",
    "eugenics": "khoa học ưu sinh",
    "fine racehorse": "ngựa đua tốt",
    "all phases": "tất cả giai đoạn",
    "superstition": "mê tín dị đoan",
    "disruptive behaviour": "hành vi phá rối",
    "futurism": "chủ nghĩa tương lai",
    "crowded train": "tàu đông đúc; tàu chật",
    "customer satisfaction": "sự hài lòng của khách hàng",
    "envy": "ghen tị; đố kị",
    "widow": "góa phụ",
    "hug": "ôm; cái ôm",
    "patient": "bệnh nhân; kiên nhẫn",
    "daily report": "báo cáo hàng ngày",
    "catcher": "người bắt bóng (bóng chày)",
    "autism": "tự kỷ",
    "abdomen": "bụng; vùng bụng",
    "abdominal cavity": "khoang bụng",
    "dance performance": "buổi biểu diễn múa",
    "group dancing": "múa tập thể",
    "floating": "nổi; trôi nổi",
    "awe": "kính sợ; ngưỡng mộ",
    "experienced": "có kinh nghiệm",
    "bride": "cô dâu",
    "poor hitting": "khả năng đánh kém",
    "reserve fund": "quỹ dự trữ",
    "armaments": "vũ trang; khí tài",
    "consumer": "người tiêu dùng",
    "bi quan": "bi quan",
    "criminal": "tội phạm; kẻ tội phạm",
    "criminal intent": "ý định phạm tội",
    "judicial trial": "phiên tòa xét xử",
    "bottle opener": "dụng cụ mở nắp chai",
    "ballot box": "hòm phiếu",
    "bookcase": "tủ sách; giá sách",
    "backstroke (swimming)": "bơi ngửa",
    "silver cup": "cúp bạc",
    "crushing defeat": "thất bại thảm hại",
    "crushing": "nghiền nát; đánh bại hoàn toàn",
    "activity": "hoạt động; tính hoạt động",
    "configurable": "có thể cấu hình",
    "pet cat": "mèo cưng",
    "stray cat": "mèo hoang",
    "bent back": "lưng còng; lưng cúi",
    "acknowledgement": "sự thừa nhận; xác nhận",
    "breakwater": "đê chắn sóng",
    "income tax": "thuế thu nhập",
    "persuasion": "thuyết phục",
    "flight": "chuyến bay; sự bay",
    "advanced course": "khóa học nâng cao",
    "elementary education": "giáo dục tiểu học",
    "safety device": "thiết bị an toàn",
    "stage setting": "bối cảnh sân khấu",
    "enshrinement": "thờ phụng; đặt lên bàn thờ",
    "stealing": "ăn cắp; trộm cắp",
    "mysterious thief": "tên trộm bí ẩn",
    "plagiarism": "đạo văn; sao chép trái phép",
    "fallen tree": "cây đổ; cây gãy",
    "developing country": "nước đang phát triển",
    "registered trademark": "nhãn hiệu đã đăng ký",
    "registration number": "số đăng ký",
    "unclimbed mountain": "núi chưa ai leo",
    "personal delivery": "giao tận tay; giao trực tiếp",
    "aptitude test": "kiểm tra năng khiếu",
    "suitable age": "độ tuổi phù hợp",
    "garden tree": "cây cảnh vườn",
    "gardener": "người làm vườn",
    "forked road": "ngã ba đường; đường rẽ",
    "asking price": "giá yêu cầu; giá niêm yết",
    "circuit breaker": "cầu dao; bộ ngắt mạch",
    "fragmentary": "manh mún; từng mảnh vụn",
    "detection": "phát hiện; dò tìm",
    "mineral exploration": "thăm dò khoáng sản",
    "detector": "máy dò; thiết bị phát hiện",
    "abdication": "thoái vị; từ chức",
    "eviction": "trục xuất; đuổi ra khỏi",
    "batter": "người đánh bóng (bóng chày)",
    "batting average": "tỷ lệ đánh trúng",
    "batting order": "thứ tự đánh bóng",
    "coexistence": "cùng tồn tại; chung sống",
    "extra pay": "phụ cấp; tiền thêm",
    "mutation": "đột biến",
    "natural gas": "khí thiên nhiên",
    "criminal liability": "trách nhiệm hình sự",
    "earned run": "điểm ghi được (bóng chày)",
    "heavy responsibility": "trách nhiệm nặng nề",
    "accumulation": "tích lũy; tích tụ",
    "cumulonimbus cloud": "mây vũ tích; mây giông",
    "careful selection": "lựa chọn cẩn thận",
    "ejaculation": "xuất tinh",
    "exquisite": "tinh tế; tuyệt đẹp",
    "spraying": "phun xịt",
    "deep breath": "hít thở sâu",
    "deep crimson": "đỏ thẫm",
    "deepening": "đào sâu; tăng chiều sâu",
    "circumstances": "hoàn cảnh; tình huống",
    "evergreen": "thường xanh; cây xanh quanh năm",
    "dehumidification": "khử ẩm",
    "assistant official": "quan phụ tá; trợ lý quan chức",
    "great help": "sự giúp đỡ lớn",
    "history": "lịch sử; lý lịch",
    "disposable": "dùng một lần; vứt bỏ",
    "execution": "thi hành; hành quyết",
    "alchemist": "nhà giả kim thuật",
    "inn": "nhà trọ; quán trọ",
    "longstanding desire": "mong muốn lâu dài",
    "branch (office)": "chi nhánh (văn phòng)",
    "(finger) ring": "nhẫn (đeo ngón tay)",
    "duodenum": "tá tràng",
    "assassination": "ám sát",
    "additional income": "thu nhập thêm",
    "annual income": "thu nhập hàng năm",
    "champagne": "rượu champagne",
    "drinking alcohol": "uống rượu",
    "drinking party": "tiệc nhậu",
    "acquaintance": "người quen biết",
    "intellectual": "trí thức; người có học",
    "(divine) revelation": "sự mặc khải (thần thánh)",
    "exhibition": "triển lãm; cuộc trưng bày",
    "unofficial announcement": "thông báo không chính thức",
    "portrait": "chân dung; ảnh chân dung",
    "(raw) material": "nguyên liệu thô",
    "artificial respiration": "hô hấp nhân tạo",
    "respiratory organs": "cơ quan hô hấp",
    "indefinite": "không xác định; vô thời hạn",
    "minimum": "tối thiểu",
    "(present) address": "địa chỉ hiện tại",
    "modern society": "xã hội hiện đại",
    "modernistic": "hiện đại; theo chủ nghĩa hiện đại",
    "antigen": "kháng nguyên",
    "atom": "nguyên tử",
    "civil rights": "quyền dân sự",
    "claim rights": "khiếu nại quyền lợi",
    "conditioned reflex": "phản xạ có điều kiện",
    "criminal case": "vụ án hình sự",
    "essential condition": "điều kiện cần thiết",
    "meeting": "cuộc họp; gặp mặt",
    "patrol": "tuần tra",
    "kinh doanh": "kinh doanh",
    "lord": "lãnh chúa; chúa tể",
    "tyrant": "bạo chúa; kẻ độc tài",
    "leather shoes": "giày da",
    "sports shoes": "giày thể thao",
    "even number": "số chẵn",
    "image": "hình ảnh; hình dáng",
    "occasionally": "thỉnh thoảng; đôi khi",
    "dinosaur": "khủng long",
    "phobia": "chứng ám ảnh sợ hãi",
    "talented": "tài năng; có tài",
    "wisdom": "trí tuệ; sự khôn ngoan",
    "marginal profits": "lợi nhuận biên",
    "(written) report": "báo cáo (bằng văn bản)",
    "appeal hearing": "phiên tòa kháng cáo",
    "seal engraving": "khắc con dấu",
    "evening": "buổi tối; chiều tối",
    "structure": "cấu trúc; kết cấu",
    "facing upward": "ngửa mặt lên; hướng lên trên",
    "hereafter": "từ nay về sau; sau này",
    "introversion": "hướng nội",
    "climate": "khí hậu; bầu không khí",
    "symptoms": "các triệu chứng",
    "accidental shooting": "bắn nhầm; bắn trúng ngoài ý muốn",
    "anachronism": "điều lỗi thời; sự không hợp thời",
    "miscalculation": "tính toán sai; nhận định sai",
    "interaction": "tương tác",
    "automatic control": "kiểm soát tự động",
    "black smoke": "khói đen",
    "enthusiastic performance": "màn trình diễn nhiệt tình",
    "dignified appearance": "dáng vẻ oai nghiêm",
    "great achievement": "thành tựu lớn",
    "karate": "karate (võ thuật)",
    "sumo": "sumo (đấu vật Nhật)",
    "judo": "judo (võ Nhật)",
    "kendo": "kendo (kiếm đạo)",
    "samurai": "samurai; võ sĩ",
    "ninja": "ninja",
    "shogun": "tướng quân; shogun",
    "shogunate": "chính quyền shogun",
    "geisha": "geisha",
    "kimono": "kimono (áo truyền thống)",
    "tatami": "tatami (chiếu truyền thống)",
    "shrine": "đền thờ Thần đạo",
    "temple": "chùa; đền",
    "torii": "cổng torii",
    "sake": "rượu sake",
    "miso": "miso (tương đậu)",
    "sushi": "sushi",
    "sashimi": "sashimi",
    "ramen": "mì ramen",
    "tempura": "tempura (đồ chiên)",
    "onsen": "suối nước nóng",
    "anime": "anime (hoạt hình Nhật)",
    "manga": "manga (truyện tranh Nhật)",
    "haiku": "haiku (thơ ngắn Nhật)",
    "calligraphy": "thư pháp",
    "origami": "origami (nghệ thuật gấp giấy)",
    "bonsai": "bonsai (cây cảnh)",
    "ikebana": "ikebana (cắm hoa)",
    "tai chi": "thái cực quyền",
    "acupuncture": "châm cứu",
    "herbal medicine": "y học thảo dược",
    "feudal lord": "lãnh chúa phong kiến",
    "peasant": "nông dân",
    "merchant": "thương nhân",
    "artisan": "thợ thủ công",
    "warrior": "chiến binh",
    "monk": "nhà sư; tu sĩ",
    "priest": "linh mục; tu sĩ",
    "nun": "ni cô; nữ tu",
    "emperor": "thiên hoàng; hoàng đế",
    "empress": "hoàng hậu",
    "prince": "hoàng tử",
    "princess": "công chúa",
    "noble": "quý tộc",
    "commoner": "thường dân",
    "constitution": "hiến pháp",
    "parliament": "quốc hội; nghị viện",
    "cabinet": "nội các",
    "minister": "bộ trưởng",
    "secretary": "thư ký; bộ trưởng",
    "governor": "thống đốc",
    "mayor": "thị trưởng",
    "treaty": "hiệp ước; điều ước",
    "alliance": "liên minh",
    "diplomacy": "ngoại giao",
    "colony": "thuộc địa",
    "empire": "đế quốc",
    "revolution": "cách mạng",
    "reform": "cải cách",
    "ideology": "hệ tư tưởng",
    "democracy": "dân chủ",
    "republic": "cộng hòa",
    "dictatorship": "độc tài",
    "communism": "chủ nghĩa cộng sản",
    "capitalism": "chủ nghĩa tư bản",
    "socialism": "chủ nghĩa xã hội",
    "nationalism": "chủ nghĩa dân tộc",
    "colonialism": "chủ nghĩa thực dân",
    "imperialism": "chủ nghĩa đế quốc",
    "propaganda": "tuyên truyền",
    "census": "điều tra dân số",
    "statistics": "thống kê",
    "gross domestic product": "tổng sản phẩm quốc nội (GDP)",
    "inflation": "lạm phát",
    "deflation": "giảm phát",
    "recession": "suy thoái kinh tế",
    "interest rate": "lãi suất",
    "exchange rate": "tỷ giá hối đoái",
    "tariff": "thuế quan",
    "subsidy": "trợ cấp",
    "stock market": "thị trường chứng khoán",
    "bond": "trái phiếu",
    "dividend": "cổ tức",
    "merger": "sáp nhập",
    "acquisition": "mua lại",
    "bankruptcy": "phá sản",
    "lawsuit": "vụ kiện",
    "settlement": "dàn xếp; giải quyết",
    "verdict": "phán quyết",
    "sentence": "bản án; câu",
    "conviction": "kết tội; niềm tin",
    "acquittal": "tha bổng",
    "parole": "tạm tha",
    "probation": "thử thách; quản chế",
    "forensic": "pháp y",
    "autopsy": "khám nghiệm tử thi",
    "DNA": "ADN",
    "fingerprint": "dấu vân tay",
    "testimony": "lời khai; chứng cứ",
    "evidence": "bằng chứng",
    "witness": "nhân chứng",
    "defendant": "bị cáo",
    "plaintiff": "nguyên đơn",
    "attorney": "luật sư",
    "judge": "thẩm phán",
    "jury": "bồi thẩm đoàn",
    "appeal": "kháng cáo",
    "litigation": "tố tụng",
}

VIET_CHARS = set('àáảãạăắặằẳẵâấầẩẫậđèéẻẽẹêếềệểễìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵÀÁẢÃẠĂẮẶẰẲẴÂẤẦẨẪẬĐÈÉẺẼẸÊẾỀỆỂỄÌÍỈĨỊÒÓỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÙÚỦŨỤƯỨỪỬỮỰỲÝỶỸỴ')
VI_WORDS = set(['mua','bai','bay','boi','bon','cai','cam','can','chay','chi','cho','co','com','con','cua','dau','dep','dia','do','doc','don','duoc','em','gan','gio','hat','hoa','hoi','ket','khu','la','loai','luc','may','mien','mo','mot','muon','nay','ngay','ngo','nguoi','nha','nhau','nhe','nhieu','nho','nuoc','phai','phan','qua','roi','sau','su','ta','tai','tam','tan','tap','ten','tiet','tim','tinh','toan','toc','toi','ton','trang','tri','trong','trung','ung','viec','vu','xa','xay','xe','xin','xu','hay','the','va','khong','cung','dang','tren','duoi','ngoai','tu','so','den','vi','nhu','khi','neu','thi','vay','biet','ngan','tem','tay','xem','kho','lat','lau','leo','lua','luon','mai','man','mat','men','met','nau','nhat','nhin','nong','nua','pho','pha','quan','quay','que','quoc','ran','rap','rat','rau','roi','ruot','sao','say','sen','sinh','son','sua','tac','tan','tang','tao','them','thoc','thoi','thu','thua','thuc','tien','tiep','tom','tot','tre','treo','tro','trong','truoc','tuoi','van','vao','vat','ve','ven','vit','voi','vua','xa','xanh','xuong'])

def is_english(s):
    if not s: return False
    if any(c in VIET_CHARS for c in s): return False
    if not any(c.isalpha() for c in s): return False
    if s[0].isupper(): return False  # Proper noun
    words = s.lower().replace(r'[^a-z ]', '').split()
    if all(w in VI_WORDS or len(w) <= 1 for w in words): return False
    return True

def fix_file(path, levels):
    content = path.read_text(encoding='utf-8')
    fixed = 0
    for en_m, vi_m in VI.items():
        # Match "m":"en_m" in words arrays
        pattern = r'("m":"' + re.escape(en_m) + r'")'
        replacement = f'"m":"{vi_m}"'
        new_content, count = re.subn(pattern, replacement, content)
        if count:
            content = new_content
            fixed += count
            print(f"  {path.name}: '{en_m}' → '{vi_m}'")
    path.write_text(content, encoding='utf-8')
    return fixed

total = 0
# Scan ALL level files (N3-classified kanji may live in n2.js due to reclassification)
for lv in ['n5', 'n4', 'n3', 'n2', 'n1']:
    path = JS / f'kanji-data-{lv}.js'
    n = fix_file(path, [lv.upper()])
    total += n
    print(f"  {lv.upper()}: {n} words fixed")

print(f"\nTổng: {total} nghĩa đã dịch")

# Rebuild combined
print("Rebuilding kanji-data.js...")
parts = []
for lv in ['n5', 'n4', 'n3', 'n2', 'n1']:
    c = (JS / f'kanji-data-{lv}.js').read_text(encoding='utf-8')
    start = c.index('['); end = c.rindex(']') + 1
    inner = c[start+1:end-1].strip().rstrip(',')
    if inner: parts.append(inner)
(JS / 'kanji-data.js').write_text(
    'window.KANJI_DATA = [\n' + ',\n'.join(parts) + '\n];\n',
    encoding='utf-8'
)
print("Done.")
