#!/usr/bin/env python3
"""
KOERU — Cài đặt Git hooks.

Chạy một lần sau khi clone repo:
  python tools/install_hooks.py

Hooks được cài:
  .git/hooks/pre-commit  → gọi tools/pre_commit_check.py
    Chặn commit nếu Excel mới hơn JS output.
"""
import os
import sys
import stat
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOOKS_DIR = ROOT / ".git" / "hooks"


def install_pre_commit() -> bool:
    hook_path = HOOKS_DIR / "pre-commit"

    # Tìm python executable phù hợp
    # Git Bash trên Windows dùng path Unix-style
    hook_content = """\
#!/bin/sh
# KOERU pre-commit hook — generated by tools/install_hooks.py
# Chặn commit nếu Excel chưa được sync sang JS
cd "$(git rev-parse --show-toplevel)" || exit 1
python tools/pre_commit_check.py
exit $?
"""
    hook_path.write_text(hook_content, encoding="utf-8", newline="\n")

    # Thêm quyền thực thi (cần thiết trên Unix/macOS/Git Bash)
    current = hook_path.stat().st_mode
    hook_path.chmod(current | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    print(f"  ✅ pre-commit   → {hook_path.relative_to(ROOT)}")
    return True


def main() -> int:
    print("KOERU — Cài đặt Git hooks")
    print("─" * 40)

    if not HOOKS_DIR.exists():
        print("❌ Không tìm thấy .git/hooks")
        print("   Đảm bảo chạy từ root của repo và đây là git repository.")
        return 1

    # Kiểm tra hook cũ
    pre_commit = HOOKS_DIR / "pre-commit"
    if pre_commit.exists():
        content = pre_commit.read_text(encoding="utf-8", errors="replace")
        if "pre_commit_check" in content:
            print("ℹ️  pre-commit hook đã tồn tại — ghi đè bằng phiên bản mới nhất")
        else:
            print("⚠️  Tìm thấy pre-commit hook từ nguồn khác")
            print("   Hook hiện tại:")
            for line in content.splitlines()[:5]:
                print(f"     {line}")
            answer = input("   Ghi đè? [y/N] ").strip().lower()
            if answer != "y":
                print("   Bỏ qua.")
                return 0

    install_pre_commit()
    print()
    print("✅ Hoàn tất. Hook sẽ chạy tự động mỗi lần git commit.")
    print()
    print("   Test thủ công:")
    print("     python tools/pre_commit_check.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
