"""
patch_vi_meanings.py — Dịch toàn bộ EN meanings còn lại sang tiếng Việt
Dùng mapping toàn diện và logic thông minh để đạt ~95%+ coverage
"""
import re, sys
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).parent.parent

# ══════════════════════════════════════════════════════════════════════════════
# BIG VI TRANSLATION TABLE — N5 + N4 JLPT (toàn diện)
# ══════════════════════════════════════════════════════════════════════════════
VI = {
    # Màu sắc
    "blue":"xanh lam; xanh","red":"đỏ","yellow":"vàng","white":"trắng",
    "black":"đen","black; dark":"đen; tối","green":"xanh lá","color":"màu sắc",
    "pink":"hồng","purple":"tím","orange":"cam","grey":"xám","brown":"nâu",
    "blue (color)":"màu xanh lam",
    # Số đếm
    "one":"một","two":"hai","three":"ba","four":"bốn","five":"năm",
    "six":"sáu","seven":"bảy","eight":"tám","nine":"chín","ten":"mười",
    "ten (~)":"mười (~)","hundred":"một trăm","thousand":"nghìn",
    "ten thousand":"mười nghìn","hundred million":"một trăm triệu",
    "zero":"không","20 years old":"20 tuổi",
    "five things":"năm cái","five days; fifth day of the month":"năm ngày; ngày mùng năm",
    "seven days; seventh day (of the month)":"bảy ngày; ngày mùng bảy",
    "nine days; ninth day of the month":"chín ngày; ngày mùng chín",
    "ten days; tenth day of the month":"mười ngày; ngày mùng mười",
    # Thực phẩm / đồ uống
    "breakfast":"bữa sáng","rice (cooked); meal":"cơm; bữa ăn",
    "(green) tea":"trà (xanh)","black tea":"trà đen; hồng trà",
    "sake; alcohol":"rượu sake; rượu","beef":"thịt bò",
    "chicken (lit., bird)":"gà (thịt gà)","chicken meat":"thịt gà",
    "meat":"thịt","salt":"muối","soy sauce":"nước tương",
    "confections, sweets, snack":"đồ ngọt; bánh kẹo; đồ ăn vặt",
    "(hard) candy":"kẹo cứng","plate, dish":"đĩa","rice bowl":"bát cơm; chén",
    "chopsticks":"đũa","a boxed lunch":"hộp cơm; bento",
    "delicious, tasty":"ngon; ngon miệng","a bath":"tắm; bồn tắm",
    "café":"quán cà phê",
    "soup; broth":"súp; canh","juice; fruit juice":"nước ép; nước trái cây",
    "bread":"bánh mì","butter":"bơ","coffee":"cà phê",
    "curry (abbr. for curry and rice)":"cà ri (cà ri cơm)",
    "milk":"sữa","wine":"rượu vang","beer":"bia",
    "vegetable(s)":"rau","fruit":"trái cây",
    "fish":"cá","egg":"trứng","tofu":"đậu phụ","noodle":"mì; bún",
    "soba (buckwheat noodle)":"mì soba","ramen":"mì ramen",
    "udon":"mì udon","tempura":"tempura (đồ chiên giòn)",
    "sushi":"sushi (cơm cuộn)","rice ball":"cơm nắm; onigiri",
    # Cơ thể
    "foot; leg":"bàn chân; chân","head":"đầu","hand":"bàn tay",
    "tooth":"răng","stomach":"bụng; dạ dày","body; health":"cơ thể; sức khỏe",
    "eye":"mắt","ear":"tai","nose":"mũi","mouth":"miệng","face":"khuôn mặt",
    "hair":"tóc","finger":"ngón tay","shoulder":"vai","knee":"đầu gối",
    "back":"lưng","chest":"ngực","arm":"cánh tay","neck":"cổ",
    "blood":"máu","pain, ache":"cơn đau","fever":"sốt","cold (illness)":"cảm lạnh",
    "cold, flu":"cảm lạnh; cúm","headache":"đau đầu","stomachache":"đau bụng",
    # Gia đình
    "(my) older brother (humble)":"anh trai (tôi)","(my) older sister (humble)":"chị gái (tôi)",
    "younger sister (humble)":"em gái (tôi)","younger brother":"em trai",
    "siblings (humble), brothers and sisters":"anh chị em",
    "uncle, middle-aged man":"chú; bác","aunt":"cô; dì; bác gái",
    "adult":"người lớn; trưởng thành","man, male":"đàn ông; nam",
    "woman, female":"phụ nữ; nữ","great number of people":"rất nhiều người",
    "grandfather, male senior citizen":"ông nội/ngoại","grandmother, female senior-citizen":"bà nội/ngoại",
    "policeman (friendly term)":"chú cảnh sát","husband (own)":"chồng (của mình)",
    "wife (own)":"vợ (của mình)","son":"con trai","daughter":"con gái",
    "child":"trẻ em; con","baby":"em bé","family":"gia đình",
    "parent":"cha mẹ","father":"bố; cha","mother":"mẹ",
    "couple":"cặp đôi","student":"học sinh; sinh viên","teacher":"giáo viên",
    "doctor; physician":"bác sĩ","nurse":"y tá","friend":"bạn bè",
    "foreigner":"người nước ngoài","guest":"khách",
    "college student, university student":"sinh viên đại học",
    # Địa điểm
    "house, home":"nhà; ngôi nhà","pond":"ao","sea, beach":"biển; bãi biển",
    "sea":"biển","entrance (to a house or a building)":"sảnh; cửa ra vào",
    "toilet, restroom, bathroom (lit., a place to wash one's hands)":"nhà vệ sinh; toilet",
    "embassy":"đại sứ quán","café":"quán cà phê","park (public)":"công viên",
    "north":"phía bắc","south":"phía nam","east":"phía đông","west":"phía tây",
    "left (direction)":"bên trái","right (direction)":"bên phải",
    "~ side":"phía ~; bên ~","nearby; in the neighborhood":"gần đây; khu xung quanh",
    "countryside":"vùng nông thôn","city":"thành phố","town":"thị trấn",
    "village":"làng","island":"hòn đảo","mountain":"núi","river":"sông",
    "lake":"hồ","forest":"rừng","beach":"bãi biển","sky":"bầu trời",
    "garden":"vườn","yard":"sân","road, street":"đường phố","bridge":"cầu",
    "corner":"góc","hill, slope":"đồi; dốc","stairs":"cầu thang",
    "stairs, staircase":"cầu thang","underground, subway":"tàu điện ngầm",
    "bus stop":"trạm xe buýt","station":"ga tàu","platform (train)":"sân ga",
    "airport":"sân bay","post office":"bưu điện","bank":"ngân hàng",
    "hospital":"bệnh viện","school":"trường học","library":"thư viện",
    "bookstore":"hiệu sách","supermarket":"siêu thị","department store":"trung tâm thương mại",
    "(abbr.) department store":"trung tâm thương mại","market":"chợ",
    "police station":"đồn cảnh sát","museum":"bảo tàng","hotel":"khách sạn",
    "restaurant":"nhà hàng","parking lot":"bãi đỗ xe","factory":"nhà máy",
    "building":"tòa nhà","office":"văn phòng","room":"căn phòng",
    "living room":"phòng khách","bedroom":"phòng ngủ","kitchen":"nhà bếp",
    "bathroom":"phòng tắm","hall, lobby":"sảnh; hành lang","ceiling":"trần nhà",
    "outside":"bên ngoài","inside":"bên trong","suburb":"ngoại ô",
    "neighborhood":"khu phố","place where things are sold":"nơi bán hàng",
    "rooftop":"sân thượng",
    # Đồ vật
    "pencil":"bút chì","(flower) vase":"bình hoa","paper":"giấy",
    "postal (postage) stamps":"tem thư","a ticket":"vé","shoes, footwear":"giày",
    "socks":"tất; vớ","wallet":"ví tiền","a lock; a key":"khóa; chìa khóa",
    "ashtray":"gạt tàn thuốc","postcard":"bưu thiếp","a map":"bản đồ",
    "a watch; a clock":"đồng hồ","soap":"xà phòng","men's suit":"bộ vest nam",
    "dictionary":"từ điển","magazine, journal":"tạp chí","newspaper":"báo",
    "book":"sách","letter (mail)":"lá thư","bag, basket":"túi; giỏ",
    "glasses":"kính mắt","umbrella":"ô; dù","gloves":"găng tay",
    "hat, cap":"mũ","scarf":"khăn quàng cổ","coat":"áo khoác",
    "shirt":"áo sơ mi","skirt":"váy","trousers":"quần dài",
    "sweater":"áo len","shoes":"giày","socks":"tất",
    "handkerchief":"khăn tay","tie, necktie":"cà vạt",
    "shirt (lit: white shirt), business shirt":"áo sơ mi công sở",
    "camera":"máy ảnh","guitar":"đàn guitar","piano":"đàn piano",
    "radio":"đài radio","television, TV":"tivi","telephone":"điện thoại",
    "computer":"máy tính","notebook":"máy tính xách tay; vở",
    "key":"chìa khóa","card":"thẻ; thiệp","match":"que diêm",
    "pen":"bút","ball-point pen":"bút bi","eraser":"tẩy",
    "ruler":"thước","scissors":"kéo","tape":"băng dán",
    "table":"bàn","chair":"ghế","bed":"giường","sofa":"ghế sofa",
    "desk":"bàn làm việc","shelf":"giá; kệ sách","window":"cửa sổ",
    "door (Western style)":"cánh cửa","door (Japanese style)":"cửa trượt Nhật",
    "elevator":"thang máy","heater (lit: stove)":"lò sưởi","air conditioner":"máy lạnh",
    "spoon":"cái thìa","fork":"nĩa","knife":"dao","cup":"ly; tách",
    "plate":"đĩa","bowl":"bát; chén","pot":"nồi","pan":"chảo",
    "bicycle":"xe đạp","motorcycle (lit: auto-bi(ke))":"xe máy",
    "taxi":"taxi","bus":"xe buýt","train":"tàu hỏa","car":"ô tô",
    "a tumbler; a glass":"ly thủy tinh","pocket":"túi áo",
    "button":"nút; cúc áo","pocket":"túi","stamp":"tem thư",
    "receipt":"biên lai","form, document":"biểu mẫu; tờ đơn",
    "calendar":"lịch","map":"bản đồ","ticket":"vé","business card":"danh thiếp",
    "passport":"hộ chiếu","luggage, baggage":"hành lý","gift":"quà tặng",
    "swimming pool":"hồ bơi","stereo":"dàn âm thanh stereo",
    "text; text book":"giáo trình; sách giáo khoa",
    # Tính từ
    "hot (in reference to weather), warm":"nóng (thời tiết); ấm",
    "hot (objects)":"nóng (đồ vật)","kind, warm(hearted), thick, deep":"tốt bụng; dày; sâu",
    "cold (in reference to weather)":"lạnh (thời tiết)","dark, gloomy":"tối; u ám",
    "narrow; not spacious":"hẹp; chật","heavy; serious":"nặng; nghiêm trọng",
    "light, non-serious, minor":"nhẹ; nhẹ nhàng",
    "near, close by, short":"gần; ngắn","far (away), distant":"xa",
    "strong, powerful":"mạnh; mạnh mẽ","cute, adorable":"dễ thương",
    "pretty, clean, tidy":"đẹp; sạch; gọn","splendid; enough, tolerably":"tuyệt; được rồi",
    "same, identical":"giống; như nhau","various":"đa dạng; nhiều loại",
    "disagreeable, detestable, unpleasant":"khó chịu; ghét",
    "big":"to; lớn","near, close":"gần","gradually, by degrees":"dần dần",
    "just, right, exactly":"đúng; chính xác","not very; surplus":"không lắm; thừa",
    "cloudiness, cloudy weather":"trời âm u; trời mây",
    "soft (in reference to texture), tender":"mềm; mềm mại",
    "discourtesy, impoliteness; Excuse me":"vô lễ; Xin lỗi",
    "useless, no good, hopeless":"vô ích; không được; vô vọng",
    "distinction, different":"sự khác biệt; khác nhau",
    "boring, dull; insignificant":"nhàm chán; không quan trọng",
    "bright (in reference to personality or weather); cheerful":"sáng; vui vẻ",
    # Trạng từ / Chức năng
    "all, everyone, everybody":"tất cả; mọi người",
    "all right, surely, certainly":"chắc chắn; nhất định",
    "straight, quickly":"thẳng; nhanh chóng",
    "firmly, steady":"vững chắc; kiên định",
    "generally, usually":"nói chung; thường",
    "finally, at last":"cuối cùng; rốt cuộc",
    "as I thought, absolutely":"đúng như nghĩ; đương nhiên",
    "mostly, almost":"hầu hết; gần như",
    "together":"cùng nhau","various, diverse":"đa dạng; phong phú",
    "It's ok (all right); No need to worry; Everything is under control":"ổn; không sao",
    "many, much":"nhiều","someone":"ai đó","what":"gì; cái gì",
    "what sort of ~":"~ loại gì","gradually":"dần dần",
    "not very; surplus":"không lắm; thừa",
    "spirit, mood":"tinh thần; tâm trạng",
    "intention, plan":"dự định; ý định",
    "and, like that":"và; như vậy",
    "yes (informal), all right (ok)":"ừ; ok",
    # Thời gian
    "yesterday":"hôm qua","this week":"tuần này","tonight, this evening":"tối nay",
    "year after next":"năm kia","month of year":"tháng (trong năm)",
    "(number of) months":"(số) tháng","~ weeks":"~ tuần","~ hours":"~ giờ",
    "~ years old":"~ tuổi","~ o'clock (time)":"~ giờ",
    "at the time of ~":"vào lúc ~","year, age":"năm; tuổi","~ years":"~ năm",
    "~ day of the month, for ~ days":"ngày ~; ~ ngày",
    "~ day of the month":"ngày ~ trong tháng",
    "New Year, New Year's Day":"Năm Mới; ngày đầu năm",
    # Động từ (còn thiếu)
    "to be (a person, animate)":"ở; có (người, sinh vật)",
    "to be (inanimate objects)":"có; ở (đồ vật)","to be, to have":"có; tồn tại",
    "to need":"cần","to put in":"bỏ vào; cho vào",
    "to put; to lay; to place":"để; đặt","to bathe, to shower":"tắm; tắm vòi",
    "to get up (e.g., from sleeping); to happen":"dậy; thức dậy; xảy ra",
    "to return something":"trả lại","to go back, to go home, to return":"về nhà",
    "to teach, to inform, to instruct":"dạy; hướng dẫn",
    "to finish, to close":"kết thúc; đóng",
    "to become cloudy, to become dim":"trở nên u ám","to erase, to delete, to turn off power":"xóa; tắt",
    "to be bothered, to have difficulty":"gặp khó khăn",
    "to answer, to reply":"trả lời","to bloom":"nở (hoa)",
    "to raise (stretch out) hands, to raise (e.g., umbrella)":"giơ tay; giương ô",
    "to cut; to hang up (a phone)":"cắt; cúp máy",
    "to put on (clothes above your waist); to wear":"mặc (áo); mặc quần áo",
    "to arrive at, to reach":"đến; tới nơi","to appear, to leave":"xuất hiện; rời đi",
    "to come to a halt":"dừng lại","to take (a photo), to make (a film)":"chụp ảnh; quay phim",
    "to learn":"học","to put (things) side by side; to line up":"xếp cạnh nhau",
    "(something) begins":"bắt đầu","to lose something":"làm mất",
    "to buy":"mua","beginning, start":"bắt đầu",
    "to get on, to ride in, to board":"lên xe; đi xe",
    "walk, stroll":"đi dạo","health(y), energetic":"khỏe; năng động",
    "to cease, to stop":"ngừng; dừng",
    "to snap, to break; to bend":"bẻ; gãy; gập",
    "to break, to break down":"làm hỏng; vỡ",
    "to pick up (something), to find":"nhặt lên",
    "to be (polite), to exist":"ở; có (kính ngữ)",
    "to bake, to grill":"nướng",
    "preparation of lessons (for class)":"chuẩn bị bài; học trước",
    "worry, concern":"lo lắng","surface; front; outside":"bề mặt; phía trước",
    "~ meeting":"cuộc họp ~; hội ~",
    "barber's (shop)":"tiệm cắt tóc nam",
    "pronunciation":"cách phát âm",
    "to steal; to rob":"trộm; cướp",
    "to step on, to tread on":"đạp; dẫm",
    "~ district, ~ ward, ~ borough":"quận ~; khu ~",
    "to live":"sống","gasoline, petrol":"xăng",
    "to sound, to ring (v.i.)":"kêu; vang",
    "exercise":"bài tập; tập thể dục",
    "to move (house)":"dọn nhà; chuyển chỗ ở",
    "~ language":"tiếng ~","word, language":"từ; ngôn ngữ",
    "Yen":"yên (đơn vị tiền tệ Nhật)",
    "country; place of origin":"đất nước; quê hương",
    "katakana":"katakana (bảng chữ cái)",
    "wind, breeze":"gió","-- honorific form for 人 (ひと) --; way of doing":"cách; người (kính ngữ)",
    "Music":"âm nhạc","counter for occurrences (~ times)":"lần ~",
    "counter for stories (floors) of a building":"tầng ~",
    "counter for small items (e.g., fruits, cups)":"cái ~ (đồ nhỏ)",
    "counter for books":"quyển ~","counter for vehicles; machines":"chiếc ~",
    "counter for people":"người ~","counter for cupfuls":"ly ~; chén ~",
    "cat":"mèo","dog":"chó","bird":"chim","fish":"cá",
    "now":"bây giờ","today":"hôm nay","tomorrow":"ngày mai",
    "dislike":"không thích; ghét","liking, fondness, love":"thích; yêu thích",
    "very like-able, like very much":"rất thích; yêu thích lắm",
    "same":"giống; như nhau",
    "cleaning, sweeping":"dọn dẹp; quét",
    "It's ok (all right); No need to worry; Everything is under control":"ổn; không sao",
    "song":"bài hát","a song":"bài hát",
    "door (Japanese style)":"cánh cửa kiểu Nhật",
    "place":"nơi; chỗ","next to, next door to":"kế bên",
    "lukewarm":"hơi ấm; ấm ấm",
    "music":"âm nhạc","sport(s)":"thể thao",
    "apartment (abbr.)":"căn hộ chung cư",
    "afterwards (later); in the future; the rest; since then":"sau đó; tương lai; phần còn lại",
    "future; recent, previous":"tương lai; gần đây; trước đây",
    "it takes (amount of time, money) (v.i.)":"mất (thời gian, tiền)",
    "near, close, beside; Japanese traditional buckwheat noodle":"gần; mì soba",
    "length, height":"chiều dài; chiều cao",
    "home; house; my place":"nhà; nhà tôi",
    "year before last":"năm kia (quá khứ)",
    "(abbr.) kilo (kilogram)":"ki-lô (kilogram)",
    "(abbr.) kilo (kilometer)":"ki-lô (kilomet)",
    "gram":"gam","meter":"mét",
    "tape recorder":"máy ghi âm băng","table":"bàn",
    "test":"bài kiểm tra","television, TV":"tivi",
    "door (Western style)":"cánh cửa","bathroom; toilet":"nhà vệ sinh",
    "news":"tin tức","notebook":"vở; sổ tay","a party":"bữa tiệc",
    "bed":"giường","pet":"thú cưng","pen":"bút","ball-point pen":"bút bi",
    "pocket":"túi áo","mailbox; post, position":"hộp thư; bưu điện",
    "button":"nút","hotel":"khách sạn","match":"que diêm",
    "radio cassette player":"máy radio cassette","record":"đĩa nhạc",
    "shirt":"áo sơ mi","shower":"tắm vòi sen","skirt":"váy",
    "heater (lit: stove)":"lò sưởi","spoon":"cái thìa","sport(s)":"thể thao",
    "trousers":"quần dài","sweater":"áo len","zero":"số không",
    "handkerchief":"khăn tay","film (roll of)":"cuộn phim",
    "swimming pool":"hồ bơi","fork":"nĩa","a page":"trang",
    "coat; court (e.g., tennis)":"áo khoác; sân tennis",
    "coffee":"cà phê","a tumbler; a glass":"ly thủy tinh",
    "elevator":"thang máy","guitar":"đàn guitar","a class":"lớp học",
    "butter":"bơ","bread":"bánh mì","a boxed lunch":"hộp cơm",
    "camera":"máy ảnh","curry (abbr. for curry and rice)":"cà ri",
    "calendar":"lịch","(hard) candy":"kẹo cứng",
    "please, kindly, by all means":"xin mời; làm ơn",
    "Ah!, Oh!":"Ồ!; Ôi!","yes":"vâng; có","no, not at all":"không",
    "Hello? (used on the phone)":"A-lô? (điện thoại)",
    "come now, well":"nào; thôi","then, well, so":"vậy thì",
    "well, well then":"vậy thì; thôi","however; but":"tuy nhiên; nhưng",
    "but, however":"nhưng","and; furthermore":"và; hơn nữa",
    "and then, after that":"và rồi; sau đó","very (much), greatly, exceedingly":"rất; vô cùng",
    "always, usually, every time, never (with neg. verb)":"luôn luôn; thường",
    "already; again; more":"đã; rồi; thêm","yet, still, besides":"vẫn còn; chưa",
    "more":"thêm; hơn","immediately, soon":"ngay; ngay lập tức",
    "slowly, at ease":"từ từ; thong thả",
    "frequently, often (much); well, skillfully":"thường; giỏi",
    "straight (ahead), direct":"thẳng; thẳng phía trước",
    "a little, somewhat; just a little, somewhat":"một chút",
    "only ~, just ~, as ~":"chỉ ~","et cetera":"vân vân",
    "at a time":"mỗi lần","past; to exceed, ~ too much":"quá ~",
    "plural suffix":"hậu tố số nhiều",
    "about, toward, approximately (time)":"khoảng (thời gian)",
    "approximate (quantity)":"khoảng chừng","honorable ~ (honorific)":"~ (kính ngữ)",
    "Mr. ~, Ms. ~":"anh/chị/ông/bà ~","feel":"cảm thấy ~",
    "you":"bạn; anh; chị","this one":"cái này","that one":"cái đó",
    "that one (over there)":"cái kia","which one":"cái nào",
    "this way (polite)":"phía này (lịch sự)",
    "this person (polite); this way (polite)":"người này; phía này (lịch sự)",
    "this person; this direction; this side":"người này; hướng này",
    "over there":"đằng kia","that place, there; bottom, sole":"nơi đó; đế",
    "here, this place":"ở đây","where, what place":"ở đâu",
    "which (one) (way); where (polite)":"cái nào; ở đâu (lịch sự)",
    "how, in what way":"như thế nào","why, for what reason":"tại sao",
    "why (same as どうして)":"tại sao","when":"khi nào",
    "how many, how old":"bao nhiêu; mấy tuổi","how much, how many":"bao nhiêu",
    "what, what kind of":"cái gì; loại nào","such, like this":"như thế này",
    "that, like that":"như vậy","this":"cái này","that":"cái đó",
    "which":"cái nào","who":"ai","good":"tốt; ngon","bad; unpleasant":"xấu; tệ",
    "terrible (in reference to food), unappetizing, unpleasant (taste)":"dở; không ngon",
    "noisy; annoying":"ồn; phiền","boring, dull; insignificant":"nhàm chán",
    "bustling, busy":"nhộn nhịp; đông đúc","splendid, fine":"tuyệt vời",
    "there isn't, doesn't have":"không có","all right; can do":"được rồi; có thể",
    "to meet, to see":"gặp","to open, to become open":"mở; mở ra",
    "to open (v.t.)":"mở (ngoại)","to raise, to lift":"nâng; đưa lên",
    "to wash":"rửa; giặt","to walk":"đi bộ","to say":"nói",
    "to go":"đi","to come":"đến; tới","to return, to go home":"về nhà",
    "to do":"làm","to do, to try; to wear small items (e.g., necktie, watch, etc.)":"làm; thử; đeo",
    "to turn on (e.g., a light); to take":"bật; lấy",
    "to turn off, to switch off":"tắt","to become":"trở thành",
    "to be able to (to accomplish)":"có thể; làm được",
    "to eat":"ăn","to drink":"uống","to sleep, to go to bed":"ngủ",
    "to get up; to wake up":"dậy; thức dậy",
    "to put on (items below your waist)":"mặc (quần áo dưới)",
    "to wear (on head, body, etc.)":"đội; mặc; đeo",
    "to put on, to wear (items above the waist)":"mặc (áo)",
    "to wear, to put on (e.g., a hat on the head)":"đội; đeo",
    "to put on, to wear (glasses, shoes, etc.)":"đeo (kính); mang (giày)",
    "to read":"đọc","to write":"viết","to listen, to hear":"nghe",
    "to speak, to talk":"nói; nói chuyện","to understand":"hiểu",
    "to understand, to know":"hiểu; biết","to know":"biết","to think":"nghĩ",
    "to remember, to memorize":"nhớ; ghi nhớ","to forget":"quên",
    "to look, to watch, to see":"nhìn; xem","to show":"chỉ; cho xem",
    "to wait":"đợi; chờ","to stand":"đứng","to sit":"ngồi",
    "to enter":"vào","to exit, to leave":"ra; rời",
    "to put in; to insert":"bỏ vào","to take out":"lấy ra",
    "to take, to pick up":"lấy; cầm","to give":"cho; tặng",
    "to give (to me)":"cho tôi","to receive":"nhận",
    "to borrow":"mượn; vay","to lend":"cho mượn","to use":"dùng",
    "to make, to create":"làm; tạo","to cook":"nấu ăn","to cut":"cắt",
    "to put, to place":"để; đặt","to take a photo":"chụp ảnh",
    "to take a bath":"tắm","to wash (the face, hands)":"rửa mặt; rửa tay",
    "to clean (the house)":"dọn dẹp nhà","to live, to reside":"sống; cư trú",
    "to work":"làm việc","to study, to learn":"học","to teach":"dạy",
    "to ask":"hỏi","to answer":"trả lời","to explain":"giải thích",
    "to begin, to start":"bắt đầu","to end, to finish":"kết thúc",
    "to continue":"tiếp tục","to stop":"dừng",
    "to run":"chạy","to swim":"bơi","to play (games, sports)":"chơi",
    "to sing":"hát","to dance":"nhảy","to draw (a picture)":"vẽ",
    "to write (a letter)":"viết thư","to call (by name), to invite":"gọi; mời",
    "to dial/call (e.g., phone); to sit down":"gọi điện; ngồi xuống",
    "to open (a door, window)":"mở (cửa)","to close (a door, window)":"đóng (cửa)",
    "to fall (rain, snow)":"rơi; đổ (mưa, tuyết)",
    "to cry (of birds, insects)":"kêu (chim, côn trùng)",
    "to travel, to make a trip":"du lịch","to ride (a vehicle)":"đi xe",
    "to get off (a vehicle)":"xuống xe","to change (train, bus)":"đổi (tàu, xe)",
    "to turn (a direction)":"rẽ; quẹo","to cross (a road, bridge)":"qua đường",
    "to climb":"leo; trèo","to pull":"kéo","to push":"đẩy",
    "to throw":"ném","to catch":"bắt","to hit":"đánh",
    "to touch, to feel":"chạm; sờ","to break (something)":"làm vỡ",
    "to break (intransitive)":"vỡ; gãy","to lose (a thing)":"mất",
    "to find":"tìm thấy","to look for":"tìm kiếm",
    "to meet, to encounter":"gặp","to marry":"kết hôn",
    "to be born":"sinh ra","to die":"chết","to send":"gửi",
    "to take (a photo)":"chụp ảnh",
    "to do; to give (to pets, parents, siblings, etc.)":"làm; cho (thú cưng...)",
    "to step on, to tread on":"đạp; dẫm",
    "to steal; to rob":"trộm; cướp","to live":"sống",
    "to cease, to stop":"ngừng; dừng",
    "to snap, to break; to bend":"bẻ; gãy; gập",
    "to break, to break down":"làm hỏng",
    "to pick up (something), to find":"nhặt lên",
    "to bake, to grill":"nướng",
    # Tạp
    "Yen":"yên (tiền Nhật)","katakana":"katakana",
    "hiragana":"hiragana","kanji":"chữ Hán (Kanji)",
    "JLPT":"JLPT (kỳ thi năng lực tiếng Nhật)",
    "Japanese language":"tiếng Nhật",
    "place where things are sold":"nơi bán hàng",
    "rooftop":"sân thượng",
    "suburb":"ngoại ô",
    "exercise":"tập thể dục; bài tập",
    "pronunciation":"cách phát âm",
    "~ meeting":"cuộc họp ~",
    "barber's (shop)":"tiệm cắt tóc nam",
    "gasoline, petrol":"xăng",
    "stereo":"dàn âm thanh",
    "text; text book":"giáo trình; sách giáo khoa",
    "distinction, different":"sự khác biệt; khác",
    "worry, concern":"lo lắng",
    "surface; front; outside":"bề mặt; phía trước",
    "spirit, mood":"tinh thần; tâm trạng",
    "intention, plan":"dự định",
    "college student, university student":"sinh viên đại học",
    "preparation of lessons (for class)":"chuẩn bị bài học",
    "soft (in reference to texture), tender":"mềm; mềm mại",
    "useless, no good, hopeless":"vô ích; không được",
    "yes (informal), all right (ok)":"ừ; ok",
    "discourtesy, impoliteness; Excuse me":"vô lễ; Xin lỗi",
    "motorcycle (lit: auto-bi(ke))":"xe máy",
    "as I thought, absolutely":"đúng như nghĩ; đương nhiên",
    "New Year, New Year's Day":"Năm Mới",
    "mostly, almost":"hầu hết; gần như",
}


def translate(en_text, js_map=None, word=None):
    if not isinstance(en_text, str) or not en_text.strip():
        return ''
    # 1. Từ JS DB
    if word and js_map and word in js_map:
        return js_map[word]
    stripped = en_text.strip()
    # 2. Match exact
    if stripped in VI:
        return VI[stripped]
    # 3. Match bỏ ngoặc đơn
    base = re.sub(r'\s*\([^)]*\)\s*$', '', stripped)
    if base in VI:
        return VI[base]
    # 4. Chuyển lower
    lower = stripped.lower()
    for k, v in VI.items():
        if k.lower() == lower:
            return v
    # 5. Fallback
    return en_text


def load_js_words():
    mapping = {}
    for lv in ['n5', 'n4', 'n3', 'n2', 'n1']:
        txt = (ROOT / "js" / f"kanji-data-{lv}.js").read_text(encoding='utf-8')
        for block in re.finditer(r'words:\[([^\]]+)\]', txt):
            raw = block.group(1)
            for w in re.finditer(r'"w":"([^"]+)"[^}]*?"m":"([^"]+)"', raw):
                word, meaning = w.groups()
                if word not in mapping:
                    mapping[word] = meaning
    return mapping


if __name__ == '__main__':
    js_map = load_js_words()

    for level, src, vocab_sheet, word_col, meaning_en_col in [
        ('N5', ROOT/"input/excel/KOERU_JLPT_N5_Vocab_Kanji_OnKun_HanViet.xlsx",
         'Vocab_N5', 'Từ vựng / Expression', 'Nghĩa nguồn EN'),
        ('N4', ROOT/"input/excel/KOERU_JLPT_N4_Vocab_Kanji_OnKun_HanViet.xlsx",
         'Vocab_N4', 'Từ vựng', 'Nghĩa EN nguồn'),
    ]:
        df = pd.read_excel(src, sheet_name=vocab_sheet)
        df['Nghĩa VI'] = df.apply(
            lambda r: translate(r[meaning_en_col], js_map, r[word_col]), axis=1
        )

        def is_still_en(s):
            if not isinstance(s, str): return False
            viet = 'àáảãạăắặằẳẵâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ'
            if any(c in viet for c in s.lower()): return False
            return bool(re.search(r'[a-zA-Z]{4,}', s))

        df['Cần kiểm tra'] = df['Nghĩa VI'].apply(is_still_en)
        vi_done = (~df['Cần kiểm tra']).sum()
        total = len(df)
        print(f"{level}: {vi_done}/{total} Việt hoá ({100*vi_done/total:.1f}%) | còn {total-vi_done} cần review")

        # Show còn EN
        still = df[df['Cần kiểm tra'] == True][[word_col,'Nghĩa VI']]
        if len(still) > 0:
            print(f"  Còn EN ({len(still)} từ):")
            for _, r in still.head(20).iterrows():
                print(f"    {r[word_col]:20s} → {r['Nghĩa VI']}")
