#!/usr/bin/env python3
"""Patch all remaining English meanings in kanji-data.js with Vietnamese translations."""
import re

VI = {
    "大注目": "chú ý rất nhiều",
    "目くじら": "khóe mắt",
    "正木": "cây hoa mộc (Euonymus japonicus)",
    "二本立て": "chiếu hai phim liên tiếp",
    "想像力": "sức tưởng tượng",
    "第三勢力": "thế lực thứ ba",
    "農工": "nông nghiệp và công nghiệp",
    "去年": "năm ngoái",
    "葬り去る": "đưa vào quên lãng",
    "去来": "đến và đi",
    "期成同盟": "liên minh thực hiện mục tiêu",
    "町村": "thị trấn và làng xã",
    "低姿勢": "giữ thái độ khiêm tốn",
    "低血圧": "huyết áp thấp",
    "低周波": "tần số thấp",
    "実弟": "em trai ruột",
    "出走": "tham gia cuộc đua",
    "近畿": "vùng Kinki (Osaka, Kyoto, Nara)",
    "月始": "đầu tháng",
    "始球式": "ném bóng khai mạc",
    "門松": "trang trí thông mừng năm mới",
    "待たせる": "làm người khác phải chờ",
    "待たす": "làm người khác phải chờ",
    "沿海州": "các tỉnh miền biển Nga",
    "県人会": "hội đồng hương",
    "県人": "người dân tỉnh đó",
    "小鳥": "chim non, chim con",
    "黒色": "màu đen",
    "軽機関銃": "súng máy hạng nhẹ",
    "暑さ": "cái nóng (thời tiết)",
    "遠来": "đến từ xa",
    "漢方薬": "thuốc thảo dược Trung Quốc",
    "漢人": "người Hán",
    "街頭": "trên đường phố",
    "初頭": "đầu (thế kỷ...)",
    "消防庁": "Cơ quan Phòng cháy chữa cháy",
    "防戦": "chiến đấu phòng thủ",
    "香典返し": "quà tặng lại đổi lấy tiền phúng điếu",
    "送り返す": "gửi trả lại",
    "努めて": "cố gắng hết sức",
    "努める": "cố gắng (làm gì đó)",
    "冬季": "mùa đông",
    "簡易保険": "bảo hiểm nhân thọ bưu điện",
    "湖底": "đáy hồ",
    "独り子": "con một",
    "独りっ子": "con một",
    "草案": "bản thảo (bài phát biểu, dự luật...)",
    "草野球": "bóng chày sân cỏ",
    "単産": "công đoàn ngành đơn",
    "解約": "hủy hợp đồng",
    "愛社": "tận tụy với công ty",
    "愛憎": "yêu và ghét",
    "指導主事": "giám sát giáo viên của chính phủ",
    "雨量": "lượng mưa",
    "難波": "Naniwa (tên cũ của vùng Osaka)",
    "育種": "chăn nuôi, lai tạo giống",
    "和洋折衷": "kết hợp phong cách Nhật và Tây",
    "警察庁": "Cơ quan Cảnh sát Quốc gia",
    "珠算": "tính toán trên bàn tính",
    "集散": "tập trung và phân phối",
    "蓄財": "tích lũy tài sản",
    "罪状": "tính chất tội phạm",
    "在勤": "đang làm việc tại",
    "再来月": "tháng sau nữa",
    "容姿": "diện mạo và hình dáng",
    "虚礼": "thủ tục rỗng tuếch",
    "令和": "thời đại Reiwa (từ 1/5/2019)",
    "悪路": "đường xấu",
    "慰労": "ghi nhận công lao",
    "腕組": "khoanh tay",
    "港湾局": "Cơ quan Cảng biển",
    "恋心": "tình cảm yêu đương",
    "歴程": "lộ trình, hành trình",
    "病歴": "tiền sử bệnh",
    "樹齢": "tuổi cây",
    "学齢": "tuổi đi học",
    "肉類": "các loại thịt",
    "感涙": "nước mắt xúc động",
    "緑風": "gió đầu hè",
    "大輪": "hoa to",
    "英領": "lãnh thổ Anh",
    "総領事": "tổng lãnh sự",
    "奈良": "Nara (thành phố, tỉnh)",
    "修了": "hoàn thành (khóa học)",
    "終了後": "sau khi kết thúc",
    "米粒": "hạt gạo",
    "流れ作業": "hệ thống dây chuyền sản xuất",
    "流失": "bị cuốn trôi",
    "党略": "chiến thuật đảng phái",
    "年率": "lãi suất hàng năm",
    "連絡先": "thông tin liên lạc",
    "絡まる": "bị vướng vào",
    "神頼み": "cầu xin thần linh",
    "頼み込む": "xin khẩn cầu",
    "食欲": "thèm ăn",
    "水溶液": "dung dịch nước",
    "預貸率": "tỷ lệ cho vay/tiền gửi",
    "投与": "dùng thuốc",
    "運輸省": "Bộ Giao thông vận tải",
    "毛筆": "bút lông",
    "文面": "nội dung văn bản",
    "百家争鳴": "trăm nhà đua tiếng",
    "地鳴り": "tiếng ầm dưới đất",
    "未発": "trước khi sự kiện xảy ra",
    "未遂": "mưu đồ thất bại",
    "貿易": "buôn bán, thương mại quốc tế",
    "ＬＴ貿易": "hiệp định thương mại Nhật-Trung 1962",
    "喜望峰": "Mũi Hảo Vọng",
    "棒状": "hình trụ hoặc thanh gậy",
    "暴論": "lập luận vô lý",
    "脱帽": "bỏ mũ ra",
    "桜ん坊": "quả anh đào",
    "亡き後": "sau khi chết",
    "豊年": "năm được mùa",
    "抱き合う": "ôm nhau",
    "社内報": "bản tin nội bộ công ty",
    "瑞宝章": "Huân chương Bảo kho Thiêng liêng",
    "人間国宝": "báu vật sống quốc gia",
    "国宝": "bảo vật quốc gia",
    "柳刃包丁": "dao bếp làm sashimi",
    "包みこむ": "bọc lại",
    "年の暮": "cuối năm",
    "朝令暮改": "lệnh sáng thay tối",
    "一人暮し": "sống một mình",
    "乱捕": "randori (tập judo tự do)",
    "沢辺": "bờ đầm lầy",
    "編集者": "biên tập viên",
    "中南米": "Trung và Nam Mỹ",
    "閉会": "bế mạc (lễ, sự kiện, cuộc họp)",
    "粉々": "vỡ thành mảnh vụn",
    "沸き起る": "trào dâng",
    "沸き返る": "sôi sục",
    "仏壇": "bàn thờ Phật",
    "仏師": "người làm tượng Phật",
    "同封": "kèm theo (trong thư)",
    "怖れる": "sợ hãi",
    "日本政府": "Chính phủ Nhật Bản",
    "富国強兵": "làm giàu đất nước, tăng cường quân sự",
    "国富": "của cải quốc gia",
    "画布": "vải bạt vẽ tranh sơn dầu",
    "夫唱婦随": "vợ phải nghe theo chồng",
    "秒速": "tốc độ mỗi giây",
    "時評": "bình luận thời sự",
    "樹皮": "vỏ cây",
    "桜皮": "cây bạch dương Nhật",
    "被選挙権": "quyền ứng cử",
    "信販会社": "công ty tín dụng",
    "日曜版": "ấn bản chủ nhật của báo",
    "羽子板": "vợt cầu lông cổ truyền",
    "甲板": "boong tàu",
    "海抜": "độ cao so với mực nước biển",
    "抜かる": "mắc sai lầm",
    "箱舟": "thuyền Noah",
    "大麦": "lúa mạch",
    "薄着": "ăn mặc mỏng nhẹ",
    "薄利多売": "lãi ít bán nhiều",
    "背もたれ": "lưng ghế",
    "背なか": "lưng (cơ thể)",
    "戦敗": "thua trận",
    "走破": "chạy hết cả quãng đường",
    "農学": "nông học",
    "農相": "Bộ trưởng Nông nghiệp",
    "濃縮": "cô đặc (dung dịch)",
    "悩む": "lo lắng, băn khoăn",
    "悩ます": "gây đau khổ",
    "難曲": "khúc nhạc khó",
    "軟式": "mềm (bóng mềm, tennis mềm...)",
    "鈍行": "tàu địa phương (tàu chậm)",
    "突き当り": "cuối đường, cuối hành lang",
    "不得意": "điểm yếu",
    "銅鐸": "chuông đồng thời Yayoi",
    "立ち到る": "đến (tình trạng nghiêm trọng)",
    "前人未到": "chưa ai đặt chân tới",
    "逃れる": "thoát khỏi",
    "逃げ惑う": "chạy trốn tán loạn",
    "増築": "mở rộng công trình",
    "人畜": "người và gia súc",
    "給湯": "cung cấp nước nóng",
    "寄り倒し": "hạ đối thủ khi giữ thắt lưng",
    "倒閣": "lật đổ chính phủ",
    "帰途": "trên đường về",
    "途惑う": "bối rối",
    "渡仏": "đến Pháp",
    "渡米": "đến Mỹ",
    "社殿": "tòa nhà chính đền Thần đạo",
    "適正価格": "giá hợp lý",
    "一滴": "một giọt (chất lỏng)",
    "水滴": "giọt nước",
    "泥酔": "say xỉn mèm",
    "家庭医": "bác sĩ gia đình",
    "射程": "tầm bắn",
    "停職": "đình chỉ công tác",
    "停学": "đình chỉ học",
    "追肥": "bón phân bổ sung",
    "急追": "đang truy đuổi sát",
    "撃沈": "đánh chìm tàu",
    "輸出超過": "xuất khẩu nhiều hơn nhập khẩu",
    "入超": "nhập siêu",
    "海外出張": "công tác nước ngoài",
    "郵貯": "tiết kiệm bưu điện",
    "自著": "tác phẩm của chính mình",
    "火柱": "cột lửa",
    "仲間入り": "gia nhập nhóm",
    "仲値": "giá trung bình",
    "血糖値": "mức đường huyết",
    "断交": "cắt đứt quan hệ (ngoại giao)",
    "担当": "phụ trách",
    "第三国": "nước thứ ba",
    "袋物": "túi xách và ví",
    "堪忍袋": "mức độ kiên nhẫn",
    "退室": "rời khỏi phòng",
    "日替り": "thay đổi mỗi ngày",
    "損失": "tổn thất (tài sản, lợi nhuận...)",
    "学則": "nội quy trường học",
    "細則": "quy định chi tiết",
    "憎む": "ghét",
    "日増しに": "ngày càng",
    "装身具": "phụ kiện cá nhân",
    "人間像": "hình ảnh người lý tưởng",
    "総出": "xuất hiện đồng loạt",
    "操車": "vận hành (tàu hỏa)",
    "無線操縦": "điều khiển từ xa",
    "燥ぐ": "vui vẻ ồn ào",
    "双発": "hai động cơ",
    "掃海": "quét mìn dưới biển",
    "仮想敵国": "nước thù giả định",
    "特捜": "điều tra đặc biệt",
    "善隣": "láng giềng tốt",
    "浅黒い": "da ngăm đen",
    "買占める": "mua gom hàng",
    "専任": "toàn thời gian",
    "住専": "công ty cho vay nhà ở",
    "初節供": "lễ hội đầu tiên của trẻ",
    "建設省": "Bộ Xây dựng",
    "好成績": "kết quả tốt",
    "税額": "số tiền thuế",
    "煉り製品": "sản phẩm chả cá",
    "守勢": "ở thế phòng thủ",
    "国勢調査": "điều tra dân số",
    "管制官": "kiểm soát viên không lưu",
    "法制局": "Cục Lập pháp Nội các",
    "地吹雪": "tuyết bị gió cuốn từ mặt đất",
    "芽吹く": "nảy chồi",
    "針灸": "châm cứu và cứu",
    "触れ込み": "tự giới thiệu là",
    "蒸かす": "hấp (thực phẩm)",
    "年賀状": "thiệp chúc mừng năm mới",
    "賀状": "thiệp chúc mừng năm mới",
    "四畳半": "phòng nhỏ 4,5 chiếu",
    "鉄条網": "hàng rào dây thép gai",
    "鑑賞": "thưởng thức nghệ thuật",
    "論功行賞": "trao thưởng theo công lao",
    "居城": "lâu đài của lãnh chúa",
    "城主": "lãnh chúa lâu đài",
    "紹介状": "thư giới thiệu",
    "厚生省": "Bộ Y tế và Phúc lợi (cũ)",
    "藍綬褒章": "Huân chương Dải Xanh",
    "照葉樹林": "rừng cây lá bóng",
    "応召": "đáp lại lệnh nhập ngũ",
    "政商": "doanh nhân có quan hệ chính trị",
    "商工": "thương mại và công nghiệp",
    "商工業": "thương mại và công nghiệp",
    "除夜": "đêm giao thừa",
    "基礎控除": "khấu trừ cơ bản",
    "営林署": "văn phòng lâm nghiệp địa phương",
    "諸々": "đủ mọi thứ",
    "情緒障害": "rối loạn cảm xúc",
    "一緒に": "cùng nhau",
    "行政処分": "biện pháp hành chính",
    "雨天順延": "hoãn lại khi trời mưa",
    "高水準": "mức cao",
    "公述": "phát biểu tại phiên điều trần công khai",
    "学術会議": "Hội đồng Khoa học Nhật Bản",
    "国民宿舎": "nhà nghỉ giá rẻ do chính quyền địa phương vận hành",
    "方舟": "thuyền Noah",
    "枝豆": "đậu edamame",
    "枯れ枝": "cành chết",
    "薬師如来": "Phật Dược sư",
    "仏具": "đồ dùng nghi lễ Phật giáo",
    "農機具": "máy móc nông nghiệp",
    "拡大均衡": "cân bằng mở rộng",
    "狭義": "nghĩa hẹp",
    "狭まる": "thu hẹp lại",
    "作況指数": "chỉ số mùa vụ",
    "挟まる": "bị kẹp giữa",
    "挟み打ち": "tấn công từ cả hai phía",
    "恐れる": "sợ hãi",
    "泣き叫ぶ": "khóc và la hét",
    "競作": "thi đua sản phẩm tốt hơn",
    "何才": "bao nhiêu tuổi",
    "良妻": "người vợ tốt",
    "新妻": "vợ mới cưới",
    "砂上": "xây trên cát",
    "砂煙": "đám bụi cát",
    "勝差": "hiệu số chiến thắng",
    "差出し人": "người gửi",
    "人混み": "đám đông",
    "混成": "hỗn hợp",
    "根拠地": "căn cứ địa",
    "骨身": "xương thịt",
    "足腰": "chân và thắt lưng",
    "腰かける": "ngồi xuống",
    "社告": "thông báo công ty",
    "焼香": "đốt hương",
    "休講": "hủy buổi học",
    "荒事": "cảnh đánh nhau (trong kịch)",
    "肯く": "gật đầu",
    "店構え": "bề ngoài cửa hàng",
    "二段構え": "chuẩn bị hai bước",
    "発効": "có hiệu lực",
    "悪天候": "thời tiết xấu",
    "相互銀行": "ngân hàng tiết kiệm tương hỗ",
    "可及的": "càng ... càng tốt",
    "黄河": "Hoàng Hà (Trung Quốc)",
    "黄瓜": "dưa chuột",
    "噴煙": "khói phun (núi lửa)",
    "土煙": "đám bụi đất",
    "終演": "kết thúc buổi biểu diễn",
    "水様液": "dung dịch trong suốt",
    "最新鋭": "hiện đại nhất",
    "雲海": "biển mây",
    "羽織": "áo khoác haori (Nhật)",
    "印画紙": "giấy in ảnh",
    "海域": "vùng biển",
    "域内": "trong phạm vi",
    "移り変り": "sự thay đổi",
    "移り変る": "thay đổi",
    "とり囲む": "bao vây",
    "民生委員": "ủy viên phúc lợi khu vực",
    "に依ると": "theo (ai đó)",
    "依存症": "phụ thuộc (rượu, ma túy...)",
    "挨拶": "lời chào hỏi",
    "年頭挨拶": "lời chúc mừng năm mới",
    "少し宛": "dần dần từng chút",
    "一尉": "đại úy (lực lượng không quân, lục quân)",
    "茨城大学": "Đại học Ibaraki",
    "茨城県警": "Cảnh sát tỉnh Ibaraki",
    "哀咽": "nấc nghẹn vì đau buồn",
    "耳鼻咽喉": "tai mũi họng",
    "握らす": "để người khác nắm tay",
    "握力": "lực nắm tay",
    "扱い方": "cách xử lý",
    "嵐が丘": "Đồi gió hú (tiểu thuyết Emily Brontë)",
    "宇宙線嵐": "bão tia vũ trụ",
    "国威": "uy tín quốc gia",
    "気の所為": "chỉ do tưởng tượng",
    "寄付行為": "hành động quyên góp",
    "畏れる": "kính sợ",
    "陰画紙": "giấy in ảnh âm bản",
    "見え隠れ": "khi ẩn khi hiện",
    "隠くす": "che giấu",
    "松韻": "tiếng nhạc gió qua rừng thông",
    "防疫": "phòng ngừa dịch bệnh",
    "悦んで": "vui lòng",
    "悦ばす": "làm ai vui sướng",
    "観閲": "kiểm duyệt (quân đội)",
    "閲覧": "duyệt web",
    "犬猿の仲": "như chó với mèo",
    "旺盛": "tràn đầy (năng lượng)",
    "小信天翁": "chim hải âu Laysan",
    "仙翁": "cây hoa lychnis",
    "襲名": "kế thừa nghệ danh",
    "謝恩会": "tiệc cảm ơn",
    "佳作": "tác phẩm tốt",
    "嫁ぎ先": "gia đình nhà chồng",
    "共稼ぎ": "vợ chồng cùng kiếm sống",
    "羽斑蚊": "muỗi Anopheles",
    "一条縞蚊": "muỗi vằn châu Á",
    "雅文": "văn phong tao nhã",
    "雅楽": "nhã nhạc cung đình Nhật",
    "滑空": "lướt qua không khí",
    "八釜しい": "được bàn tán nhiều",
    "鎌倉時代": "thời đại Kamakura (1185-1333)",
    "鎌倉幕府": "Mạc phủ Kamakura (1185-1333)",
    "三冠馬": "ngựa thắng ba giải lớn",
    "勘案": "cân nhắc kỹ lưỡng",
    "持堪える": "cầm cự",
    "寛ぐ": "thư giãn",
    "憾み": "điều đáng tiếc",
    "憾む": "hối tiếc",
    "入棺": "đặt vào quan tài",
    "歓送": "tiễn đưa nồng nhiệt",
    "弛緩": "thư giãn (cơ bắp)",
    "艦長": "thuyền trưởng tàu chiến",
    "頑張って": "cố lên",
    "経企庁": "Cơ quan Kế hoạch Kinh tế (giải thể 2001)",
    "日本企業": "công ty Nhật Bản",
    "棄権": "từ chối bỏ phiếu",
    "欺く": "lừa dối",
    "騎乗": "cưỡi ngựa",
    "立脚": "dựa trên",
    "健脚": "đi bộ giỏi",
    "冷却期間": "thời gian hòa dịu",
    "凶作": "mùa màng thất bát",
    "享年": "tuổi khi mất",
    "恭賀新年": "chúc mừng năm mới",
    "脅える": "trở nên sợ hãi",
    "謹賀新年": "kính chúc năm mới",
    "口吟む": "khe khẽ hát",
    "朝駆": "tấn công buổi sáng sớm",
    "串柿": "hồng sấy khô trên xiên",
    "掘り出す": "đào lên",
    "洞窟熊": "gấu hang (tuyệt chủng)",
    "繰り越": "số dư chuyển tiếp",
    "繰り入れ": "chuyển tiền vào",
    "傾注": "tập trung vào",
    "携行": "mang theo người",
    "携る": "tham gia vào",
    "掲揚": "kéo lên (cờ)",
    "掲載": "đăng tải",
    "鱗茎": "củ hành (lily, tulip...)",
    "遣り甲斐": "đáng để làm",
    "遣唐使": "sứ thần đến nhà Đường",
    "献上": "dâng tặng",
    "自己顕示": "tự làm mình nổi bật",
    "懸賞": "đặt tiền thưởng",
    "勤倹の風": "thói quen cần cù và tiết kiệm",
    "倹素": "tiết kiệm và đơn giản",
    "上機嫌": "tâm trạng tốt",
    "虎蛾": "một loài bướm đêm",
    "虎列剌茸": "nấm độc Galerina fasciculata",
    "木枯": "gió đông lạnh giá",
    "舌鼓": "chép miệng (vì ngon)",
    "坑内": "bên trong hầm mỏ",
    "廃坑": "đóng cửa mỏ",
    "拘束時間": "tổng số giờ làm việc",
    "控訴": "kháng cáo lên tòa cao hơn",
    "轟沈": "đánh chìm tàu ngay lập tức",
    "出獄": "ra tù",
    "昏れる": "trời tối",
    "恨む": "oán giận",
    "開墾": "khai hoang đất mới",
    "墾田": "ruộng lúa mới khai hoang",
    "唆す": "xúi giục",
    "試行錯誤": "thử và sai",
    "暫く": "một lúc",
    "暫くぶり": "lâu rồi mới gặp",
    "老人福祉": "phúc lợi người cao tuổi",
    "諮る": "tham khảo ý kiến",
    "諮問事項": "nội dung tham khảo",
    "慈愛": "tình thương (đặc biệt của cha mẹ)",
    "慈悲": "lòng từ bi",
    "滋る": "mọc um tùm",
    "国璽書": "con dấu Quốc hội Anh",
    "璽書": "văn bản có ấn của hoàng đế",
    "嫉む": "ghen tị",
    "嫉ける": "nóng bừng (do nắng)",
    "中執": "Ban chấp hành Trung ương",
    "執務": "thực hiện nhiệm vụ chính thức",
    "特赦": "ân xá đặc biệt",
    "遮断機": "thanh chắn đường sắt",
    "遮る": "ngắt, cản lại",
    "朱文金": "cá vàng shubunkin Nhật",
    "儒艮": "dugong (cá cúi)",
    "遵守": "tuân thủ (luật lệ)",
    "遵う": "đi dọc theo (sông...)",
    "庶務": "hành chính tổng hợp",
    "叙勲": "trao tặng huân chương",
    "如月": "tháng hai âm lịch",
    "抄う": "múc",
    "戊申詔書": "Chiếu thư Mậu Thân 1908",
    "草丈": "chiều cao cây lúa",
    "出来る丈": "hết sức có thể",
    "半分冗談": "nói đùa một nửa",
    "浄土真宗": "Tịnh Độ Chân tông",
    "浄土宗": "Tịnh Độ tông",
    "剰す": "để dành",
    "令嬢": "ái nữ (của gia đình tốt)",
    "嬢さん": "tiểu thư",
    "廃娼": "bãi bỏ mại dâm có phép",
    "割譲": "nhượng địa",
    "分譲": "bán từng lô đất",
    "川尻": "cửa sông",
    "侵掠": "xâm lược",
    "手振り": "cử chỉ tay",
    "浸し物": "rau luộc ướp xì dầu",
    "米審": "Hội đồng Giá Gạo",
    "刃先": "lưỡi dao",
    "疾風迅雷": "nhanh như chớp",
    "迅速果断": "nhanh và quyết đoán",
    "澄みきる": "trong vắt",
    "摂る": "dùng (bữa ăn)",
    "摂待": "tiếp đãi (ăn uống)",
    "繊切り": "thái sợi mỏng",
    "鮮度": "độ tươi",
    "遷宮": "chuyển đền thờ",
    "遷都": "dời đô",
    "他薦": "được người khác giới thiệu",
    "壮年": "tuổi tráng niên",
    "服喪": "chịu tang",
    "会葬": "dự đám tang",
    "社葬": "tang lễ công ty",
    "促成": "thúc đẩy tăng trưởng",
    "良俗": "phong tục tốt",
    "土俗": "phong tục địa phương",
    "即日": "trong cùng ngày",
    "遡る": "đi ngược dòng",
    "汰る": "rung lắc",
    "滞在中": "trong thời gian lưu trú",
    "堕とす": "làm ngã (trong judo)",
    "脱党": "rời bỏ đảng",
    "着脱": "lắp và tháo",
    "切支丹": "Kitô giáo ở Nhật thời phong kiến",
    "鍛える": "rèn giũa",
    "鋳鍛鋼": "thép đúc và rèn",
    "銃弾": "đạn súng",
    "方向音痴": "kém định hướng",
    "勧善懲悪": "thưởng thiện phạt ác",
    "教育勅語": "Chiếu chỉ Giáo dục 1890",
    "軍人勅諭": "Chiếu chỉ Quân nhân 1882",
    "撃墜": "bắn hạ máy bay",
    "一里塚": "cột mốc (cách nhau 1 ri)",
    "塩漬": "ngâm muối",
    "紡織": "kéo sợi và dệt vải",
    "徹夜": "thức cả đêm",
    "撤兵": "rút quân",
    "添乗": "đi kèm (trong chuyến đi)",
    "妬む": "ghen tị",
    "妬ける": "nóng bừng (do nắng)",
    "吐露": "bày tỏ tâm tư",
    "匿す": "che giấu",
    "反騰": "giá tăng trở lại",
    "騰貴": "tăng giá",
    "戸籍謄本": "bản sao hồ sơ gia đình",
    "胴上げ": "tung lên không trung (ăn mừng)",
    "謎染": "kiểu nhuộm có câu đố",
    "謎かけ": "đặt câu đố",
    "沖縄": "Okinawa (thành phố, tỉnh)",
    "大雑把": "cẩu thả",
    "制覇": "giành chức vô địch",
    "廃案": "dự luật bị bác bỏ",
    "間伐": "tỉa thưa định kỳ (rừng)",
    "賞罰": "thưởng và phạt",
    "農繁期": "mùa nông vụ bận rộn",
    "頒ける": "rẽ đám đông",
    "頒布権": "quyền phân phối phim",
    "蛮行": "hành vi man rợ",
    "男尊女卑": "trọng nam khinh nữ",
    "弊社": "công ty chúng tôi",
    "蔑む": "khinh bỉ",
    "偏重": "coi trọng quá mức",
    "何遍": "bao nhiêu lần",
    "町奉行": "quan chức thị trấn thời Edo",
    "薩摩芋": "khoai lang",
    "眉白": "chim hét Siberia",
    "魅入る": "mê hoặc",
    "魅かれる": "bị quyến rũ",
    "大規模": "quy mô lớn",
    "小躍り": "nhảy mừng",
    "暗躍": "hoạt động bí mật",
    "誘い出す": "nhử ra ngoài",
    "憂国": "lo lắng cho tương lai đất nước",
    "内憂外患": "lo lắng trong nước và ngoài nước",
    "執行猶予": "hoãn thi hành án",
    "起訴猶予": "tạm đình chỉ truy tố",
    "投融資": "đầu tư và cho vay",
    "融け合う": "hòa tan vào nhau",
    "雄鹿": "hươu đực",
    "両雄": "hai hào kiệt (đối thủ)",
    "沃野": "đồng bằng màu mỡ",
    "菲沃斯": "cây cà độc dược",
    "湧き起る": "trào dâng",
    "倣う": "noi theo",
    "見倣う": "học qua quan sát",
    "慶弔": "chúc mừng và chia buồn",
    "弔電": "điện chia buồn",
    "醸しだす": "tạo ra (không khí...)",
    "憧れの的": "đối tượng ngưỡng mộ",
    "憧れる": "khao khát",
    "貢献": "đóng góp",
    "川沿い": "dọc theo sông",
    "縫成": "may bằng máy",
    "覆土": "phủ đất lên hạt giống",
    "炊き込み": "nấu cùng với gạo",
    "炊き出し": "phân phát cơm",
    "就学": "bắt đầu đi học",
    "履き古し": "giày cũ mòn",
    "絵を描く": "vẽ tranh",
    "描き写す": "sao chép (tranh)",
    "破砕": "nghiền vụn",
    "腰砕け": "sụp đổ giữa chừng",
    "驚く": "ngạc nhiên",
    "驚かす": "làm ngạc nhiên",
    "輝かす": "làm sáng lên",
    "光り輝く": "tỏa sáng",
    "泣崩れる": "oà khóc",
    "跳馬": "ngựa nhảy (thể dục)",
    "走高跳": "nhảy cao có đà",
    "舞踏": "vũ điệu (đặc biệt kiểu Tây)",
    "釣り銭": "tiền thối lại",
    "撮み洗い": "giặt chỗ bẩn",
    "特殊撮影": "hiệu ứng đặc biệt",
    "高野豆腐": "đậu phụ đông khô",
    "削りとる": "bào/cạo đi",
    "おい茂る": "mọc um tùm",
    "縛り首": "treo cổ",
    "金縛り": "bị trói buộc bởi tiền",
    "絞首刑": "tử hình bằng treo cổ",
    "絞める": "siết cổ",
    "濁す": "nói mơ hồ",
    "煮干": "cá khô nhỏ giòn",
    "つくだ煮": "thực phẩm kho nước tương ngọt",
    "初診": "khám lần đầu",
    "飽く迄も": "đến tận cùng",
    "飢え死": "chết đói",
    "行政訴訟": "kiện hành chính",
    "敗訴": "thua kiện",
    "揚げもの": "đồ chiên",
    "から揚げ": "đồ chiên (đặc biệt gà rán)",
    "胴揚げ": "tung lên không trung",
    "焦げ付き": "nợ xấu",
    "妨げる": "cản trở",
    "艦載機": "máy bay trên tàu chiến",
    "慌てる": "hoảng loạn",
    "締約": "ký kết hiệp ước",
    "褒章": "huân chương",
    "嘉納": "tiếp nhận với niềm vui",
    "勧業": "khuyến khích công nghiệp",
    "勧進帳": "sổ quyên góp đền chùa",
    "眺める": "nhìn từ bên ngoài",
    "慰霊": "an ủi hồn người đã khuất",
    "揺らす": "lắc",
    "離日": "rời Nhật Bản",
    "離任": "rời nhiệm sở",
    "矢継ぎ早": "liên tiếp không ngừng",
    "予研": "Viện Y tế Quốc gia",
    "操車": "vận hành tàu",
    "店構え": "bề ngoài cửa hàng",
    "社告": "thông báo công ty",
    "慕う": "ngưỡng mộ theo",
    "営繕": "bảo trì và sửa chữa",
    "繕う": "điều trị (bệnh)",
    "高裁": "Tòa án Cấp cao",
    "赴任": "chuyển đến nơi làm mới",
    "赴く": "đến, đi đến",
    "貫通": "thông thạo",
    "促成": "thúc đẩy tăng trưởng",
    "立ち尽す": "đứng yên không nhúc nhích",
    "摘み洗い": "giặt chỗ bẩn",
    "臨床": "lâm sàng",
    "臨港": "ven cảng",
    "負惜しみ": "không chịu thừa nhận thua",
    "染織": "nhuộm và dệt",
    "漏る": "rò rỉ",
    "居据わる": "ở lại",
    "据え置き": "hoãn lại (tiết kiệm...)",
    "絶唱": "bài thơ/bài hát tuyệt vời",
    "秀作": "tác phẩm xuất sắc",
    "淡水": "nước ngọt",
    "凡退": "ra sân 1-2-3 (bóng chày)",
    "厄年": "năm xui",
    "巧走": "chạy giỏi",
    "浪華": "Naniwa (tên cũ vùng Osaka)",
    "頻度": "tần suất xảy ra",
    "淳朴": "chân thật và mộc mạc",
    "厚朴": "cây đại mộc lan Nhật",
    "病魔": "ma quỷ bệnh tật",
    "徐行": "chạy chậm (xe, tàu...)",
    "最徐行": "chạy rất chậm",
    "本欄": "cột này",
    "り患": "mắc bệnh",
    "眼前": "trước mắt",
    "耐性菌": "vi khuẩn kháng kháng sinh",
    "乳酸菌": "vi khuẩn axit lactic",
    "筋金": "thanh thép gia cường",
    "本筋": "chủ đề chính",
    "居睡り": "gật gù (trong khi ngồi)",
    "聴聞会": "phiên điều trần",
    "妊産婦": "phụ nữ mang thai và cho con bú",
    "水晶体": "thể thủy tinh mắt",
    "水晶": "thạch anh tinh khiết",
    "既往": "quá khứ",
    "幹線": "tuyến đường chính",
    "常軌": "đường lối bình thường",
    "搬入": "đưa vào",
    "減益": "giảm lợi nhuận",
    "定期購読": "đăng ký dài hạn",
    "利付債": "trái phiếu có lãi suất",
    "起債": "phát hành trái phiếu",
    "酬われる": "được đền đáp",
    "街宣車": "xe tuyên truyền",
    "宣戦": "tuyên chiến",
    "月賦": "trả góp hàng tháng",
    "裕に": "dễ dàng (đạt, vượt...)",
    "浪花": "Naniwa (tên cũ vùng Osaka)",
    "出梅": "kết thúc mùa mưa",
    "梅雨前線": "mặt trận mưa mùa",
    "芽ぶく": "nảy chồi",
    "昆布": "rong biển kombu",
    "昆虫綱": "lớp côn trùng",
    "大菩薩峠": "Kiếm đạo thiêng liêng (phim 1966)",
    "峠越え": "vượt đèo",
    "岬湾": "mũi đất và vịnh",
    "滝口": "đỉnh thác nước",
    "滝登り": "cá bơi ngược thác",
    "沼田": "ruộng đầm lầy",
    "雲散霧消": "tan như sương mù",
    "霜降": "hình thành sương muối",
    "気泡": "bọt khí",
    "渦巻": "xoáy nước, xoắn ốc",
    "渦巻く": "xoáy cuộn",
    "思潮": "xu hướng tư tưởng",
    "老松": "cây thông già",
    "夜桜": "hoa anh đào ban đêm",
    "戦跡": "chiến trường cũ",
    "航跡": "vệt sóng sau tàu",
    "毛穴": "lỗ chân lông",
    "外堀": "hào ngoài lâu đài",
    "門扉": "cánh cổng",
    "網棚": "giá hành lý trên tàu/xe buýt",
    "娘婿": "con rể",
    "女婿": "con rể",
    "鬼子母神": "Hariti (thần sinh sản và trẻ em)",
    "鬼理死丹": "Kitô giáo Nhật thời phong kiến",
    "舌戦": "cuộc chiến lời nói",
    "癖に": "mặc dù vậy",
    "口癖": "thói quen nói",
    "主峰": "đỉnh cao nhất",
    "霊前": "trước linh hồn người đã khuất",
    "鳥獣": "chim và thú hoang",
    "悲喜": "vui và buồn",
    "天台宗": "Thiên Thai tông",
    "崇高": "cao thượng, sublime",
    "崇城大学": "Đại học Sojo",
    "新約聖書": "Tân ước",
    "聖霊": "linh hồn người đã khuất",
    "大僧正": "cao tăng, đại hòa thượng",
    "記念碑": "bia kỷ niệm",
    "侮る": "coi thường",
    "地球儀": "quả cầu địa cầu",
    "愁える": "than thở, than vãn",
    "処遇": "cách đối xử",
    "最優遇": "đãi ngộ tốt nhất",
    "忠孝": "trung thành và hiếu thảo",
    "親不孝": "bất hiếu",
    "扶養": "nuôi dưỡng",
    "墓前": "trước mộ",
    "栄誉礼": "lễ chào danh dự",
    "高緯度": "vĩ độ cao",
    "早乙女": "cô gái trẻ cấy lúa",
    "一括払い": "thanh toán một lần",
    "第三紀": "kỷ Đệ Tam",
    "別項": "mục riêng",
    "斜陽": "suy tàn",
    "紙垂": "cây hornbeam",
    "国是": "chính sách quốc gia",
    "是か非か": "đúng hay sai",
    "戦端": "mở đầu chiến sự",
    "微塵切り": "băm nhỏ",
    "十字架": "cây thập tự",
    "論拠": "cơ sở lập luận",
    "人災": "thảm họa do con người",
    "干拓": "khai hoang đất từ biển",
    "弁天": "nữ thần nghệ thuật và trí tuệ",
    "新概念": "khái niệm mới",
    "概観": "cái nhìn tổng quát",
    "遊興": "ăn chơi (rượu và đàn bà)",
    "創世記": "Sáng thế ký (Kinh thánh)",
    "創世": "tạo thế giới",
    "課徴金": "phí và lệ phí",
    "徴収": "thu (phí, thuế...)",
    "正統派": "trường phái chính thống",
    "増援": "viện binh",
    "しゅん功": "hoàn thành xây dựng",
    "新約克": "New York",
    "軍属": "nhân viên dân sự trong quân đội",
    "冒す": "mạo nhận họ người khác",
    "苦慮": "suy nghĩ vắt óc",
    "司法": "tư pháp",
    "修士": "thạc sĩ",
    "授業中": "trong giờ học",
    "多湿": "độ ẩm cao",
    "湿度": "độ ẩm",
    "良識": "lẽ thường, sự khôn ngoan",
    "相似形": "hình đồng dạng",
    "似かよう": "giống nhau",
    "誌上": "trên tạp chí",
    "誌面": "trang tạp chí",
    "作詞": "viết lời bài hát",
    "江戸時代": "thời đại Edo (1603-1868)",
    "物故": "qua đời",
    "故国": "quê hương",
    "水加減": "lượng nước",
    "賢所": "điện thờ trong cung",
    "車券": "vé cá cược đua xe đạp",
    "割引券": "phiếu giảm giá",
    "京劇": "kinh kịch Trung Quốc",
    "劇画": "truyện tranh kịch tính",
    "送迎": "tiễn và đón",
    "出迎える": "ra đón",
    "警視庁": "Sở Cảnh sát Metropolitan",
    "農芸": "nông nghiệp và làm vườn",
    "芸文": "nghệ thuật và văn học",
    "敬老": "kính trọng người cao tuổi",
    "敬愛": "kính trọng và yêu mến",
    "自由型": "tự do (bơi lội...)",
    "皇軍": "Quân đội Hoàng gia Nhật",
    "米軍": "lực lượng vũ trang Mỹ",
    "校訓": "châm ngôn trường học",
}

print("📂 Đọc kanji-data.js...")
with open("js/kanji-data.js", "r", encoding="utf-8") as f:
    content = f.read()

patched = 0
not_found = 0

for word, vi_meaning in VI.items():
    if vi_meaning is None:
        continue
    pattern = r'("w":\s*"' + re.escape(word) + r'"[^}]*"m":\s*")([^"]+)(")'

    VI_CHARS = set('àáâãèéêìíòóôõùúýăđơưạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỷỹỵÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐƠƯ')

    def replacer(m, vi=vi_meaning):
        current = m.group(2)
        if any(c in VI_CHARS for c in current):
            return m.group(0)
        return m.group(1) + vi + m.group(3)

    new_content, n = re.subn(pattern, replacer, content)
    if n > 0:
        content = new_content
        patched += n
    else:
        not_found += 1

print(f"✅ Đã dịch {patched} entries, không tìm thấy: {not_found}")

with open("js/kanji-data.js", "w", encoding="utf-8") as f:
    f.write(content)

print("💾 Đã ghi → js/kanji-data.js")
