"""N4 extra translations — toàn bộ từ còn chưa dịch"""
VI_N4 = {
    "(abbr.) building":"(viết tắt) tòa nhà",
    "(female) nurse":"y tá (nữ)",
    "(hon.) good, OK, all right":"được rồi; ổn (kính ngữ)",
    "(hon.) to give, to confer":"ban tặng; cho (kính ngữ)",
    "(humble) (polite) seeing, look at":"xem; nhìn (khiêm tốn)",
    "(humble)to say, to tell":"thưa; nói (khiêm tốn)",
    "(someone else's) child (polite)":"con (của người khác, kính ngữ)",
    "(your, her) husband":"chồng (của bạn/cô ấy, kính ngữ)",
    "-- extra-modest expression for いる --":"ở; tồn tại (khiêm tốn cực đoan)",
    "-- extra-modest expression for たべる and のむ; humble expression for もらう --":"ăn; uống; nhận (khiêm tốn cực đoan)",
    "-- honorific expression for いう --":"nói (kính ngữ)",
    "-- honorific expression for する --":"làm (kính ngữ)",
    "-- honorific expression for みる --":"xem; nhìn (kính ngữ)",
    "-- honorific form of 食べる (たべる) and 飲む (のむ) --":"ăn; uống (kính ngữ)",
    "-- humble expression for あげる --":"cho; tặng (khiêm tốn)",
    "America, U.S.A.":"nước Mỹ; Hoa Kỳ",
    "Buddhist temple":"chùa; đền Phật giáo",
    "I see; I now understand":"Tôi hiểu rồi; Vậy à",
    "Mr. (junior) ~, master ~":"cậu ~; em ~",
    "a Japanese inn":"nhà trọ kiểu Nhật (ryokan)",
    "a lecture":"bài giảng; buổi giảng",
    "a little while ago":"một lúc trước; vừa rồi",
    "a parent":"cha mẹ; bố mẹ",
    "about, concerning":"về; liên quan đến",
    "accessory":"phụ kiện; đồ trang sức",
    "accident":"tai nạn; sự cố",
    "according to ~":"theo ~; dựa theo ~",
    "after every ~":"mỗi ~; sau mỗi ~",
    "air, atmosphere":"không khí; bầu không khí",
    "alcohol":"rượu; đồ uống có cồn",
    "all, completely":"tất cả; hoàn toàn",
    "an introduction":"lời giới thiệu",
    "and (conj.), thereupon, because of that":"và; vì vậy",
    "and, then":"và rồi; sau đó",
    "announcer":"người dẫn chương trình; phát thanh viên",
    "answer, response":"câu trả lời; phản hồi",
    "appearance, manner, shape, form, posture":"diện mạo; cách thức; hình dạng; tư thế",
    "approximately; in most cases; in general; to begin with (same as もともと)":"khoảng; nhìn chung; ban đầu",
    "art gallery, art museum":"triển lãm nghệ thuật; bảo tàng mỹ thuật",
    "ashamed, embarrassed":"xấu hổ; ngượng ngùng",
    "at last, finally":"cuối cùng; rốt cuộc",
    "beautiful, lovely":"đẹp; xinh đẹp",
    "branch, twig":"cành cây; nhánh",
    "breakdown":"hỏng hóc; sự cố kỹ thuật",
    "but, although":"nhưng; mặc dù",
    "calling on someone who is ill, visit":"thăm bệnh; thăm người ốm",
    "cause, origin, source":"nguyên nhân; nguồn gốc",
    "certainly, of course":"tất nhiên; đương nhiên",
    "change; balance of money returned to the purchaser":"tiền thối; tiền lẻ",
    "cherry-blossom viewing":"ngắm hoa anh đào",
    "circumstances, convenience":"hoàn cảnh; sự thuận tiện",
    "citizen":"công dân",
    "clearly, distinctly":"rõ ràng; rõ rệt",
    "clerk; shop-employee":"nhân viên bán hàng; nhân viên cửa hàng",
    "closet":"tủ quần áo âm tường",
    "coast, seashore":"bờ biển",
    "concert":"buổi hòa nhạc; concert",
    "condition, state, health":"tình trạng; trạng thái; sức khỏe",
    "conference room":"phòng họp",
    "congratulation, celebration":"chúc mừng; lễ kỷ niệm",
    "consent, acceptance":"sự đồng ý; chấp thuận",
    "consultation":"tư vấn; hỏi ý kiến",
    "correct":"đúng; chính xác",
    "cotton":"bông; vải cotton",
    "curtain":"rèm cửa",
    "deep, profound":"sâu; sâu sắc",
    "degree, extent":"mức độ; phạm vi",
    "delicious; skillful; fortunate":"ngon; giỏi; may mắn",
    "department of a university":"khoa (đại học)",
    "diary, journal":"nhật ký",
    "difficult to do ~":"khó làm ~; khó ~",
    "diligent, serious":"chăm chỉ; nghiêm túc",
    "doll, figure":"búp bê; mô hình",
    "driving":"lái xe; việc lái xe",
    "economics, finance, economy":"kinh tế; tài chính",
    "education":"giáo dục",
    "electric light":"đèn điện",
    "encyclopedia, reference book":"bách khoa toàn thư; sách tham khảo",
    "errand, task, business (to take care of)":"việc vặt; nhiệm vụ; công việc",
    "escalator":"thang cuốn",
    "exhibition":"triển lãm",
    "export":"xuất khẩu",
    "expression of gratitude; thanking; gift of appreciation; bow":"lời cảm ơn; quà biếu; cúi đầu",
    "extremely":"vô cùng; cực kỳ",
    "fairly well, to a large extent, considerably, pretty much":"khá; tương đối; phần lớn",
    "far away, distant":"xa; xa xôi",
    "feast, treating (someone)":"bữa tiệc; đãi (ai đó)",
    "feeling, mood":"cảm giác; tâm trạng",
    "festival":"lễ hội",
    "fever, temperature":"sốt; nhiệt độ",
    "first (of all), to start with":"trước hết; để bắt đầu",
    "flavor, taste":"hương vị; mùi vị",
    "foodstuff, groceries":"thực phẩm; đồ tạp hóa",
    "for example, e.g.":"ví dụ; chẳng hạn",
    "freedom":"tự do",
    "from now on, after this":"từ nay trở đi; sau này",
    "gas station, service station":"trạm xăng; cây xăng",
    "geography":"địa lý",
    "girlfriend; she":"bạn gái; cô ấy",
    "good, advantage, in order to":"tốt; lợi thế; để",
    "government worker, public servant":"công chức; viên chức nhà nước",
    "gradually, soon":"dần dần; chẳng bao lâu",
    "grapes":"nho",
    "hamburger steak":"bít tết hamburger",
    "harbor, port":"cảng; bến cảng",
    "high school; senior high school":"trường trung học phổ thông",
    "hindrance, intrusion":"sự cản trở; làm phiền",
    "honorable ~":"kính ~; đáng kính ~",
    "hospitalization":"nhập viện; nằm viện",
    "however much one may ~":"dù ~ bao nhiêu đi nữa",
    "humble expression for 行く and 来る":"đi; đến (khiêm tốn)",
    "humble form of 行く (いく), 聞く (きく) and 来る (くる)":"đi; hỏi; đến (khiêm tốn)",
    "if I remember correctly; certain, definite":"nếu tôi nhớ đúng; chắc chắn",
    "if at all possible, as much as possible":"nếu có thể; càng nhiều càng tốt",
    "if possible, as much as possible":"nếu có thể; càng ~ càng tốt",
    "import":"nhập khẩu",
    "information, guidance":"thông tin; hướng dẫn",
    "injection":"mũi tiêm; tiêm thuốc",
    "injury (to animate object), hurt":"bị thương; vết thương",
    "insect":"côn trùng",
    "invitation":"lời mời",
    "it has been a long time; for the first time in a long time":"lâu rồi mới gặp; lần đầu sau thời gian dài",
    "it should be so":"lẽ ra phải thế; đương nhiên",
    "junior high school pupil":"học sinh cấp 2; học sinh trung học cơ sở",
    "just did ~, only":"vừa mới ~; chỉ",
    "kimono; Japanese traditional dress":"kimono; trang phục truyền thống Nhật",
    "kindness":"lòng tốt; sự tốt bụng",
    "knowing, acquaintance":"quen biết; người quen",
    "leaving hospital":"xuất viện; ra viện",
    "letter; character":"chữ cái; ký tự",
    "like this, this way":"như thế này; kiểu này",
    "little while":"lúc nữa; một chút",
    "living, life; to live":"cuộc sống; sinh hoạt; sống",
    "lodging, boarding house":"chỗ trọ; nhà trọ",
    "looking after; to look after":"chăm sóc; trông nom",
    "lunch break, noon recess":"giờ nghỉ trưa",
    "major; speciality":"chuyên ngành; môn chuyên",
    "match, game, competition":"trận đấu; cuộc thi",
    "member of ~":"thành viên ~",
    "metropolitan":"đô thị lớn; thủ đô",
    "middle, center":"giữa; trung tâm",
    "moreover; besides":"hơn nữa; ngoài ra",
    "most":"nhất; phần lớn",
    "never":"không bao giờ",
    "newspaper company":"tòa soạn báo; công ty báo",
    "not at all (neg. verb)":"hoàn toàn không (dùng với động từ phủ định)",
    "not at all; wholly, entirely":"hoàn toàn không; hoàn toàn",
    "number ~ sequence, ~nd; ~th":"số thứ tự ~; thứ ~",
    "occasionally":"đôi khi; thỉnh thoảng",
    "old days; past":"ngày xưa; quá khứ",
    "on the way, midway":"trên đường; giữa chừng",
    "once, one time":"một lần; một lần duy nhất",
    "oppose, opposition, resistance":"phản đối; đối lập",
    "or, otherwise":"hoặc; nếu không",
    "other than, with the exception of, excepting":"ngoại trừ; ngoài ra",
    "overcoat; over, exceeding, exaggeration":"áo khoác dài; vượt quá; phóng đại",
    "part time (esp. female part time employees)":"bán thời gian (nhân viên nữ bán thời gian)",
    "part-time job":"việc làm thêm; bán thời gian",
    "person who is specialized in ~":"người chuyên về ~; chuyên gia ~",
    "pickpocket":"kẻ móc túi",
    "police; police station":"cảnh sát; đồn cảnh sát",
    "polite, courteous, careful":"lịch sự; nhã nhặn; cẩn thận",
    "preparation":"sự chuẩn bị",
    "present, gift":"quà tặng",
    "prosperous, active, thriving":"thịnh vượng; năng động; phát đạt",
    "quarrel":"cãi nhau; tranh cãi",
    "quickly and steadily; at a rapid pace":"nhanh chóng và đều đặn; ào ào",
    "rate, ratio, percentage":"tỷ lệ; phần trăm",
    "register":"đăng ký; sổ đăng ký",
    "regret; regrettable":"tiếc; đáng tiếc",
    "reservation":"đặt chỗ; đặt trước",
    "restraint, reserve, hesitate":"kiềm chế; dè dặt; ngần ngại",
    "rich person":"người giàu",
    "rural, countryside":"nông thôn; vùng quê",
    "sandal":"dép xỏ ngón; sandal",
    "sandwich":"bánh mì sandwich",
    "screen":"màn hình; màn chiếu",
    "season (in reference to weather)":"mùa (thời tiết)",
    "shallow, superficial":"nông; nông cạn",
    "sightseeing":"tham quan; du lịch",
    "simple":"đơn giản",
    "so much, like that":"nhiều như vậy; đến mức đó",
    "so; therefore":"vì vậy; vậy nên",
    "soft; soft hat; software":"mềm; mũ mềm; phần mềm",
    "souvenir":"quà lưu niệm",
    "space, interval":"khoảng cách; khoảng không gian",
    "strange, odd":"kỳ lạ; lạ thường",
    "strange; odd; funny":"kỳ lạ; buồn cười",
    "strength, power":"sức mạnh; năng lực",
    "substitute, replacement":"thay thế; người/vật thay thế",
    "suburb, outskirts":"ngoại ô; vùng ven",
    "such, like that":"như vậy; kiểu đó",
    "such, like that, that sort of":"như vậy; loại đó",
    "suffix for familiar (female) person":"hậu tố thân mật (dành cho nữ)",
    "suitcase":"vali; túi hành lý",
    "surely, definitely, undoubtedly, certainly":"chắc chắn; nhất định",
    "surroundings":"xung quanh; môi trường xung quanh",
    "tatami mat (Japanese straw mat)":"chiếu tatami (chiếu rơm Nhật)",
    "technique, technology, skill":"kỹ thuật; công nghệ; kỹ năng",
    "telegram":"điện tín; telegram",
    "tennis":"quần vợt; tennis",
    "terrible, awful, unfair, cruel":"khủng khiếp; tệ hại; bất công",
    "terrific, great":"tuyệt vời; tuyệt",
    "thanks or owing to":"nhờ; nhờ có",
    "the month after next":"tháng kia (tương lai)",
    "the other day, recently":"hôm nọ; gần đây",
    "the professor's office; laboratory":"văn phòng giáo sư; phòng thí nghiệm",
    "the town of ~":"thị trấn ~",
    "the week after next":"tuần kia (tương lai)",
    "these days, nowadays":"dạo này; ngày nay",
    "thing(s), matter(s), fact":"sự việc; điều; thực tế",
    "this evening, tonight":"tối nay",
    "thread":"chỉ; sợi chỉ",
    "throat":"cổ họng",
    "to add (numbers)":"cộng (số); thêm",
    "to be broken, to break":"bị hỏng; vỡ",
    "to be continued":"tiếp theo; còn tiếp",
    "to be empty (in reference to people), to be less crowded":"trống; ít người; thưa",
    "to be found (v.i.), to be discovered":"được tìm thấy; được phát hiện",
    "to be started, to be switched on":"được khởi động; được bật",
    "to be surprised, to be astonished":"ngạc nhiên; kinh ngạc",
    "to be visible; -- polite verb meaning 来る (くる) --":"nhìn thấy; đến (kính ngữ)",
    "to become dirty":"trở nên bẩn",
    "to break, to be folded, to give in; to turn (a corner)":"bẻ; gập; rẽ (góc)",
    "to bully, to torment":"bắt nạt; hành hạ",
    "to burn, to be roasted":"bị đốt; bị nướng",
    "to carry out; to conduct (typically used in written language)":"thực hiện; tiến hành",
    "to change (v.i.), to be transformed, to vary":"thay đổi (nội); biến đổi",
    "to change, to alter, to vary":"thay đổi; biến đổi",
    "to check; to look up; to inquire; to search":"kiểm tra; tra cứu; hỏi",
    "to choose; to select":"chọn; lựa chọn",
    "to collapse, to break down":"sụp đổ; hỏng hóc",
    "to continue doing ~":"tiếp tục làm ~",
    "to continue, to keep up":"tiếp tục; duy trì",
    "to convey (a message); to tell, to report":"truyền đạt; báo cáo",
    "to correct (v.t.); to fix":"sửa; sửa lại",
    "to deliver (v.t.)":"giao; giao hàng",
    "to descend, to drop, to fall":"xuống; rơi; giảm",
    "to disappear, to get lost":"biến mất; mất tích",
    "to discover, to find (v.t.)":"phát hiện; tìm thấy",
    "to escape, to run away":"trốn thoát; chạy trốn",
    "to exchange, to replace":"đổi; thay thế",
    "to face, to go towards":"đối mặt; hướng về",
    "to finish doing ~":"hoàn thành ~; xong ~",
    "to gain weight":"tăng cân; béo lên",
    "to gather (v.i.), to collect":"tụ tập; thu thập",
    "to get better; to recover from illness (v.i.)":"hồi phục; bình phục",
    "to give, to do for":"cho; làm cho",
    "to go around, to revolve":"đi vòng quanh; quay",
    "to hit, to strike":"đánh; gõ",
    "to increase, to multiply":"tăng; nhân",
    "to lead, to take (a person)":"dẫn; đưa (người đi)",
    "to lose weight":"giảm cân; gầy đi",
    "to make noise, to clamor":"gây ồn; ầm ĩ",
    "to mind, to care about, to be concerned about":"bận tâm; quan tâm; lo về",
    "to move (from a house); to transfer (from a department); to shift":"chuyển (nhà); chuyển (bộ phận)",
    "to move to a new place of residence":"dọn đến chỗ ở mới",
    "to notify":"thông báo; báo",
    "to open, to become empty (vacant)":"mở; trống (không có người)",
    "to paint, to plaster":"sơn; tô; trát",
    "to part from, to separate":"chia tay; tách ra",
    "to resemble, to be similar":"giống; tương tự",
    "to search, to seek, to look for":"tìm kiếm; tìm",
    "to send, to dispatch":"gửi; phái",
    "to soak, to moisten, to pickle":"ngâm; làm ướt; muối (dưa)",
    "to stand (something) up, to erect (something)":"dựng lên; đặt đứng",
    "to start doing ~":"bắt đầu ~; bắt đầu làm ~",
    "to that degree; extent":"đến mức đó; đến vậy",
    "to think (about); to consider":"nghĩ (về); cân nhắc",
    "to transfer (trains), to change (bus, train, etc.)":"đổi tàu; đổi xe",
    "to transport, to carry":"vận chuyển; chở; mang",
    "to try one's best, to try hard, to persist":"cố gắng hết sức; kiên trì",
    "to welcome; to meet; to greet":"chào đón; đón; chào",
    "traffic, transportation":"giao thông; vận tải",
    "translation":"bản dịch; dịch thuật",
    "type, style":"loại; kiểu; phong cách",
    "unreasonable, impossible":"vô lý; không thể",
    "unusual, rare":"hiếm; bất thường",
    "urgent, sudden; steep":"khẩn cấp; đột ngột; dốc",
    "venue, meeting place":"địa điểm; nơi gặp gỡ",
    "very hard (as in 'to work hard'), with utmost effort":"hết sức cố gắng; nỗ lực hết mình",
    "very soon; in a few moments; days":"chẳng bao lâu; sắp sửa",
    "very, considerably, quite":"rất; khá; đáng kể",
    "water service, water line":"dịch vụ nước máy; đường ống nước",
    "way (of doing something)":"cách (làm gì); phương pháp",
    "weather forecast":"dự báo thời tiết",
    "wife (humble)":"vợ tôi (khiêm tốn)",
    "within, inside":"bên trong; trong phạm vi",
    "within, less (no more) than":"trong vòng; không quá",
    "wonderful; terrific":"tuyệt vời; tuyệt",
    "woods, forest":"rừng cây; rừng",
    "word processor":"máy xử lý văn bản",
    "~ Street, ~ Avenue":"phố ~; đại lộ ~",
    "~ age; period":"thời đại ~; giai đoạn ~",
    "~ ceremony; ~ style":"lễ ~; phong cách ~",
    "~ storied, separate housing":"nhà ~ tầng; nhà riêng",
    "suburb, outskirts":"ngoại ô",
    "very hard (as in \"to work hard\"), with utmost effort":"hết sức cố gắng",
}
